// AUTO-GENERATED by scripts/gen-route-ids.mjs -- do not edit by hand.
// Regenerated on every `npm run build` from the src/content/** collections.
export const articleIds = ['how-to-find-the-range', 'standard-deviation', 'standard-deviation-symbol'] as const;
export const calculatorIds = ['average', 'mean', 'mean-absolute-deviation', 'median', 'percentile', 'range', 'standard-deviation', 'variance', 'weighted-average', 'z-score'] as const;
export const categoryIds = ['combinatorics', 'descriptive-statistics', 'foundations', 'inferential-statistics', 'probability-distributions', 'regression-correlation'] as const;

export type ArticleContentId = (typeof articleIds)[number];
export type CalculatorContentId = (typeof calculatorIds)[number];
export type CategoryContentId = (typeof categoryIds)[number];
