// AUTO-GENERATED by scripts/gen-route-ids.mjs -- do not edit by hand.
// Regenerated on every `npm run build` from the src/content/** collections.
export const articleIds = ['how-to-find-the-range', 'standard-deviation', 'standard-deviation-symbol'] as const;
export const calculatorIds = ['mean', 'median', 'range', 'standard-deviation'] as const;
export const categoryIds = ['descriptive-statistics'] as const;

export type ArticleContentId = (typeof articleIds)[number];
export type CalculatorContentId = (typeof calculatorIds)[number];
export type CategoryContentId = (typeof categoryIds)[number];
