// AUTO-GENERATED by scripts/gen-route-ids.mjs -- do not edit by hand.
// Regenerated on every `npm run build` from the src/content/** collections.
export const articleIds = ['correlation-vs-causation', 'how-to-find-the-range', 'linear-regression', 'mean-absolute-deviation', 'parameter-vs-statistic', 'standard-deviation', 'standard-deviation-symbol', 'weighted-average', 'what-is-an-average'] as const;
export const calculatorIds = ['average', 'binomial-distribution', 'chi-square', 'combination', 'confidence-interval', 'correlation-coefficient', 'factorial', 'frequency-table', 'linear-regression', 'mean', 'mean-absolute-deviation', 'mean-median-mode-range', 'median', 'normal-distribution', 'outlier', 'p-value', 'percentile', 'probability', 'proportion', 'range', 'range-iqr', 'sample-size', 'standard-deviation', 't-table', 't-test', 'variance', 'weighted-average', 'z-score', 'z-table'] as const;
export const categoryIds = ['combinatorics', 'descriptive-statistics', 'foundations', 'inferential-statistics', 'probability-distributions', 'regression-correlation'] as const;

export type ArticleContentId = (typeof articleIds)[number];
export type CalculatorContentId = (typeof calculatorIds)[number];
export type CategoryContentId = (typeof categoryIds)[number];
