BEGIN TRANSACTION;
CREATE TABLE outsource_articles (
  slug                TEXT PRIMARY KEY,
  title               TEXT NOT NULL,
  category_slug       TEXT NOT NULL,
  queue_position      INTEGER NOT NULL,
  day_label           TEXT NOT NULL DEFAULT '',
  babylovegrowth_id   TEXT,
  status              TEXT NOT NULL DEFAULT 'queued',
  raw_path            TEXT,
  mdx_path            TEXT,
  images_removed      INTEGER NOT NULL DEFAULT 0,
  images_converted    INTEGER NOT NULL DEFAULT 0,
  citations_stripped  INTEGER NOT NULL DEFAULT 0,
  source_count        INTEGER,
  notes               TEXT NOT NULL DEFAULT '',
  created_at          TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO "outsource_articles" VALUES('nonparametric-tests','Nonparametric Tests: When to Use Them','data-analysis',1,'18','741024','published','outsource-content/raw/nonparametric-tests.json','src/content/articles/nonparametric-tests.mdx',2,1,1,8,'','2026-08-20 19:37:40','2026-08-20 20:30:51');
INSERT INTO "outsource_articles" VALUES('bonferroni-correction','Bonferroni Correction: A Practical Guide','experiments-causality',2,'19','741025','published',NULL,NULL,0,0,0,NULL,'','2026-08-20 19:37:40','2026-09-01 18:16:24');
INSERT INTO "outsource_articles" VALUES('mediation-analysis','Mediation Analysis','experiments-causality',3,'20','750156','published',NULL,NULL,0,0,0,NULL,'','2026-08-20 19:37:40','2026-09-01 18:16:24');
INSERT INTO "outsource_articles" VALUES('randomized-controlled-trial','Randomized Controlled Trial','experiments-causality',4,'21',NULL,'published',NULL,NULL,0,0,0,NULL,'','2026-08-20 19:37:40','2026-09-01 18:16:25');
INSERT INTO "outsource_articles" VALUES('intention-to-treat','Intention to Treat','experiments-causality',5,'22',NULL,'queued',NULL,NULL,0,0,0,NULL,'','2026-08-20 19:37:40','2026-08-20 19:37:40');
INSERT INTO "outsource_articles" VALUES('multiple-comparisons-problem','Multiple Comparisons Problem','experiments-causality',6,'23',NULL,'queued',NULL,NULL,0,0,0,NULL,'','2026-08-20 19:37:40','2026-08-20 19:37:40');
INSERT INTO "outsource_articles" VALUES('normality-tests','Normality Tests','data-analysis',7,'24',NULL,'queued',NULL,NULL,0,0,0,NULL,'','2026-08-20 19:37:40','2026-08-20 19:37:40');
INSERT INTO "outsource_articles" VALUES('holt-winters','Holt-Winters','time-series-forecasting',8,'25',NULL,'queued',NULL,NULL,0,0,0,NULL,'','2026-08-20 19:37:40','2026-08-20 19:37:40');
INSERT INTO "outsource_articles" VALUES('pearson-vs-spearman','Pearson vs Spearman','data-analysis',9,'26','795714','published','outsource-content/raw/pearson-vs-spearman.json','src/content/articles/pearson-vs-spearman.mdx',1,2,0,6,'','2026-08-20 19:37:40','2026-09-02 05:02:51');
INSERT INTO "outsource_articles" VALUES('log-transform-data','Log Transform Data','data-analysis',10,'27','796247','published','outsource-content/raw/log-transform-data.json','src/content/articles/log-transform-data.mdx',1,1,0,8,'','2026-08-20 19:37:40','2026-09-02 04:58:22');
INSERT INTO "outsource_articles" VALUES('scatter-plot-interpretation','Scatter Plot Interpretation','data-analysis',11,'28',NULL,'queued',NULL,NULL,0,0,0,NULL,'','2026-08-20 19:37:40','2026-08-20 19:37:40');
INSERT INTO "outsource_articles" VALUES('propensity-score-matching','Propensity Score Matching','experiments-causality',12,'29','796250','published','outsource-content/raw/propensity-score-matching.json','src/content/articles/propensity-score-matching.mdx',1,1,0,8,'','2026-08-20 19:37:40','2026-09-02 05:02:51');
INSERT INTO "outsource_articles" VALUES('confidence-level-vs-significance-level','Confidence Level vs Significance Level','data-analysis',13,'30','796252','published','outsource-content/raw/confidence-level-vs-significance-level.json','src/content/articles/confidence-level-vs-significance-level.mdx',2,1,0,8,'','2026-08-20 19:37:40','2026-09-02 19:43:12');
INSERT INTO "outsource_articles" VALUES('sequential-testing','Sequential Testing','experiments-causality',14,'31','795760','published','outsource-content/raw/sequential-testing.json','src/content/articles/sequential-testing.mdx',1,0,0,7,'','2026-08-20 19:37:40','2026-09-02 19:57:01');
INSERT INTO "outsource_articles" VALUES('heteroscedasticity-test','Heteroscedasticity Test','data-analysis',15,'1','799503','published','outsource-content/raw/heteroscedasticity-test.json','src/content/articles/heteroscedasticity-test.mdx',1,1,0,8,'','2026-08-20 19:37:40','2026-09-02 19:59:30');
INSERT INTO "outsource_articles" VALUES('data-visualization-best-practices','Data Visualization Best Practices','data-analysis',16,'2','796513','published','outsource-content/raw/data-visualization-best-practices.json','src/content/articles/data-visualization-best-practices.mdx',1,2,0,6,'','2026-08-20 19:37:40','2026-09-03 18:21:49');
INSERT INTO "outsource_articles" VALUES('confusion-matrix-explained','Confusion Matrix Explained','machine-learning-statistics',17,'3','800818','published','outsource-content/raw/confusion-matrix-explained.json','src/content/articles/confusion-matrix-explained.mdx',1,1,0,9,'','2026-08-20 19:37:40','2026-09-06 17:16:27');
INSERT INTO "outsource_articles" VALUES('f1-score-explained','F1 Score Explained','machine-learning-statistics',18,'4','804171','published','outsource-content/raw/f1-score-explained.json','src/content/articles/f1-score-explained.mdx',1,2,0,8,'','2026-08-20 19:37:40','2026-09-06 17:16:28');
INSERT INTO "outsource_articles" VALUES('sarima-model','SARIMA Model','time-series-forecasting',19,'5','809054','published','outsource-content/raw/sarima-model.json','src/content/articles/sarima-model.mdx',2,1,0,6,'','2026-08-20 19:37:40','2026-09-06 17:16:28');
INSERT INTO "outsource_articles" VALUES('granger-causality','Granger Causality','time-series-forecasting',20,'6','813927','published','outsource-content/raw/granger-causality.json','src/content/articles/granger-causality.mdx',0,1,0,6,'','2026-08-20 19:37:40','2026-09-06 17:16:28');
INSERT INTO "outsource_articles" VALUES('odds-ratio-interpretation','Odds Ratio Interpretation','data-analysis',21,'7','795837','published','outsource-content/raw/odds-ratio-interpretation.json','src/content/articles/odds-ratio-interpretation.mdx',3,0,1,8,'','2026-09-06 17:32:03','2026-09-06 17:53:15');
INSERT INTO "outsource_articles" VALUES('dual-axis-charts','Dual-Axis Charts','data-analysis',22,'8','795836','published','outsource-content/raw/dual-axis-charts.json','src/content/articles/dual-axis-charts.mdx',3,0,0,9,'','2026-09-06 17:32:03','2026-09-06 17:53:15');
INSERT INTO "outsource_articles" VALUES('confidence-interval-vs-prediction-interval','Confidence Interval vs Prediction Interval','data-analysis',23,'9','795835','published','outsource-content/raw/confidence-interval-vs-prediction-interval.json','src/content/articles/confidence-interval-vs-prediction-interval.mdx',2,0,8,8,'','2026-09-06 17:32:03','2026-09-06 17:53:15');
INSERT INTO "outsource_articles" VALUES('box-cox-transformation','Box-Cox Transformation','data-analysis',24,'10','795834','published','outsource-content/raw/box-cox-transformation.json','src/content/articles/box-cox-transformation.mdx',1,1,1,8,'','2026-09-06 17:32:03','2026-09-06 17:53:16');
INSERT INTO "outsource_articles" VALUES('one-tailed-vs-two-tailed','One-Tailed vs Two-Tailed Tests','data-analysis',25,'11','795679','published','outsource-content/raw/one-tailed-vs-two-tailed.json','src/content/articles/one-tailed-vs-two-tailed.mdx',1,2,0,7,'','2026-09-06 17:32:03','2026-09-13 14:04:42');
INSERT INTO "outsource_articles" VALUES('histogram-vs-boxplot','Histogram vs Boxplot','data-analysis',26,'32','851203','published','outsource-content/raw/histogram-vs-boxplot.json','src/content/articles/histogram-vs-boxplot.mdx',2,0,0,7,'','2026-09-13 13:32:12','2026-09-18 12:17:43');
INSERT INTO "outsource_articles" VALUES('multiple-regression-diagnostics','Multiple Regression Diagnostics','data-analysis',27,'33','847496','published','outsource-content/raw/multiple-regression-diagnostics.json','src/content/articles/multiple-regression-diagnostics.mdx',2,1,0,8,'','2026-09-13 13:32:12','2026-09-18 12:27:01');
INSERT INTO "outsource_articles" VALUES('misleading-graphs','Misleading Graphs','data-analysis',28,'34','843362','published','outsource-content/raw/misleading-graphs.json','src/content/articles/misleading-graphs.mdx',2,1,0,8,'','2026-09-13 13:32:12','2026-09-13 19:16:30');
INSERT INTO "outsource_articles" VALUES('false-discovery-rate','False Discovery Rate','experiments-causality',29,'35','840413','published','outsource-content/raw/false-discovery-rate.json','src/content/articles/false-discovery-rate.mdx',1,2,6,8,'','2026-09-13 13:32:12','2026-09-13 19:11:28');
INSERT INTO "outsource_articles" VALUES('conditional-probability-exercises','Conditional Probability Exercises','data-analysis',30,'36','835307','published','outsource-content/raw/conditional-probability-exercises.json','src/content/articles/conditional-probability-exercises.mdx',1,2,0,8,'','2026-09-13 13:32:12','2026-09-13 19:45:24');
INSERT INTO "outsource_articles" VALUES('communicating-uncertainty','Communicating Uncertainty','data-analysis',31,'37','830958','published','outsource-content/raw/communicating-uncertainty.json','src/content/articles/communicating-uncertainty.mdx',1,0,0,6,'','2026-09-13 13:32:12','2026-09-13 19:42:23');
INSERT INTO "outsource_articles" VALUES('interrupted-time-series','Interrupted Time Series','experiments-causality',32,'38','826410','published','outsource-content/raw/interrupted-time-series.json','src/content/articles/interrupted-time-series.mdx',1,1,0,8,'','2026-09-13 13:32:12','2026-09-13 19:36:29');
INSERT INTO "outsource_articles" VALUES('cohens-d','Cohen''s d','data-analysis',33,'39','821297','published','outsource-content/raw/cohens-d.json','src/content/articles/cohens-d.mdx',1,1,0,6,'','2026-09-13 13:32:12','2026-09-13 19:30:50');
INSERT INTO "outsource_articles" VALUES('difference-in-differences','Difference in Differences','experiments-causality',34,'40','817034','published','outsource-content/raw/difference-in-differences.json','src/content/articles/difference-in-differences.mdx',1,1,1,8,'','2026-09-13 13:32:12','2026-09-13 19:33:18');
INSERT INTO "outsource_articles" VALUES('missing-data-imputation','Missing Data Imputation','data-analysis',35,'41','854352','published','outsource-content/raw/missing-data-imputation.json','src/content/articles/missing-data-imputation.mdx',1,2,0,7,'','2026-09-13 13:46:50','2026-09-18 12:31:22');
INSERT INTO "outsource_articles" VALUES('box-plot-interpretation','Box Plot Interpretation','data-analysis',36,'42','857043','published','outsource-content/raw/box-plot-interpretation.json','src/content/articles/box-plot-interpretation.mdx',1,2,0,6,'','2026-09-13 13:46:50','2026-09-19 18:14:08');
INSERT INTO "outsource_articles" VALUES('bias-variance-tradeoff','Bias-Variance Tradeoff','machine-learning-statistics',37,'43','863134','in_review','outsource-content/raw/bias-variance-tradeoff.json','src/content/articles/bias-variance-tradeoff.mdx',1,1,0,6,'','2026-09-13 13:46:50','2026-09-19 18:03:17');
CREATE TABLE outsource_reviews (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  article_slug   TEXT NOT NULL REFERENCES outsource_articles(slug) ON DELETE CASCADE,
  passed         INTEGER NOT NULL DEFAULT 0,
  notes          TEXT NOT NULL DEFAULT '',
  created_at     TEXT NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO "outsource_reviews" VALUES(1,'nonparametric-tests',1,'Manual first-article checkpoint: check_sanitized.py 14/14, astro check 0 errors, 121/121 tests, full build 0 link violations (4530 links) / 0 meta-description violations, all 8 Sources verified 200 (Mayo Clinic dropped, verified 403), all 6 internal route ids verified real, 0 keyword collisions. Fixed primaryKeyword (was a lowercased full title w/ colon, now matches site convention) and related (was empty, now the 3 in-body Learn siblings) before publish. Published by explicit user go-ahead.','2026-08-20 20:30:50');
INSERT INTO "outsource_reviews" VALUES(2,'propensity-score-matching',0,'check_sanitized 14/14 + build gate all clean, but 2/8 Sources 403 on curl -sL final destination (Austin 2011 doi.org/10.1002/pst.433, Austin 2009 doi.org/10.1002/sim.3697 -> onlinelibrary.wiley.com, Cloudflare bot-mitigation per cf-mitigated:challenge header; Wayback confirms both were live 200 as of 2025-07-15) -- treat as hard fail per reviewer bar (4xx is hard fail, only ''no response'' is WARN), swap for accessible mirrors or get manual verification; also processor wrongly stripped internal link to /correlation-vs-causation/ claiming the article doesn''t exist -- it does (src/content/articles/correlation-vs-causation.mdx), restore as <Link to={routes.article(''correlation-vs-causation'')}>. Not published, draft untouched.','2026-09-02 04:48:07');
INSERT INTO "outsource_reviews" VALUES(3,'propensity-score-matching',1,'check_sanitized 14/14; fabrication spot-check clean (ProcessFlow/table figures traced to raw text); no keyword-cannibalization collision; all 8 Sources verified 200 and citation text matches destination content (Rosenbaum 1983 CMU PDF, both Austin PMC papers, CBPS, Wager PDF all confirmed genuine); build gate clean.','2026-09-02 04:58:22');
INSERT INTO "outsource_reviews" VALUES(4,'log-transform-data',1,'check_sanitized 14/14; fabrication spot-check clean (DataTables/TaxonomyTree traced to raw text, no invented numbers); no keyword-cannibalization collision; all 8 Sources verified live (statmodeling 403 to curl is Cloudflare bot-mitigation, confirmed genuine via Wayback 200 + title match; biostathandbook 406 to curl is plain UA block, 200 with browser UA) and citation text matches destination content; build gate clean.','2026-09-02 04:58:22');
INSERT INTO "outsource_reviews" VALUES(5,'pearson-vs-spearman',0,'check_sanitized 14/14 and no fabrication/cannibalization issues, but citation-accuracy check failed: Sources entry (and body cite at ''tutorial on correlation methods'') label https://pmc.ncbi.nlm.nih.gov/articles/PMC7779167/ as ''Comparing the Pearson and Spearman correlation coefficients across distributions and sample sizes: A tutorial using simulations and empirical data'' -- but PMC7779167 is actually Rovetta A, ''Raiders of the Lost Correlation: A Guide on Using Pearson and Spearman Coefficients to Detect Hidden Correlations in Medical Sciences'' (Cureus 2020), a different paper by a different author. The correctly-titled paper is the arXiv preprint already cited separately (arxiv.org/pdf/2408.15979). Fix: either retitle the PMC7779167 Sources entry/body link to match Raiders of the Lost Correlation, or drop it and keep only the arXiv citation. Draft untouched, not published.','2026-09-02 04:58:22');
INSERT INTO "outsource_reviews" VALUES(6,'propensity-score-matching',0,'REVERTED prior PASS: npm run build throws at render time -- KeyTakeaways.astro defaults variant to ''table'' (requires non-empty ''rows''), but this article''s <KeyTakeaways bullets={[...]} /> passes ''bullets'' without variant="bullets", so it hits the table branch with rows=undefined and throws ''KeyTakeaways: rows must be a non-empty array when variant=table'' during /propensity-score-matching/ static generation. check_sanitized 14/14, citations, fidelity, and cannibalization all still clean -- this is purely a component-prop mismatch. Fix: add variant="bullets" to the KeyTakeaways call (matches the pattern already used correctly in pearson-vs-spearman.mdx). draft reverted to true, not published.','2026-09-02 04:59:31');
INSERT INTO "outsource_reviews" VALUES(7,'propensity-score-matching',1,'Orchestrator gate: sanitizer 14/14 pre-flip; citation-accuracy audit fixed (Rosenbaum/Rubin URL, Austin PMC swaps, PMC7779167 retitled to Rovetta 2020); KeyTakeaways variant fixed; astro check 0, 121 tests, build 127 pages 0 violations.','2026-09-02 05:02:51');
INSERT INTO "outsource_reviews" VALUES(8,'pearson-vs-spearman',1,'Orchestrator gate: sanitizer 14/14 pre-flip; citation-accuracy audit fixed (Rosenbaum/Rubin URL, Austin PMC swaps, PMC7779167 retitled to Rovetta 2020); KeyTakeaways variant fixed; astro check 0, 121 tests, build 127 pages 0 violations.','2026-09-02 05:02:51');
INSERT INTO "outsource_reviews" VALUES(9,'confidence-level-vs-significance-level',1,'check_sanitized 14/0, all 8 sources verified live (200s, titles match citations), DataTable/AnnotatedChart match raw JSON, no cannibalization, astro check/tests/build all clean with page live in check-links (129 pages, 4880 links, 0 violations)','2026-09-02 19:43:12');
INSERT INTO "outsource_reviews" VALUES(10,'sequential-testing',0,'Dead source: Penn State STAT 509 alpha-spending URL (online.stat.psu.edu/stat509/book/export/html/705) no longer resolves -- 302s to course homepage (confirmed for other node IDs too, not specific to 705) and fails plain SSL verify (curl -sL w/o -k = exit 60/000); archived 2024-09-30 copy confirms real page was titled ''9.6 - Alpha Spending Function approach'', now gone. Needs a live replacement URL or citation removal. Also flag (non-blocking): ''-- Statohub'' sign-off after Statohub''s Take section is inconsistent with sibling confidence-level-vs-significance-level.mdx (commit 8f04bb4) which dropped it -- recommend dropping here too for house-style consistency, left untouched pending orchestrator decision. All other checks pass: check_sanitized 14/0, 6/7 sources verified live+title-matching (arXiv Lewis fix confirmed correct via citation_title/citation_author), 3 DataTables + 2 infographics traced to raw JSON with no fabricated values, no keyword-cannibalization collision, astro check/tests/build clean at baseline (129 pages, 4880 links, 121 tests, 0 violations).','2026-09-02 19:49:46');
INSERT INTO "outsource_reviews" VALUES(11,'heteroscedasticity-test',0,'Remove the ''> *— Statohub*'' sign-off line (line 194) after the Statohub''s Take/Recommended-Default section — house style forbids it; section itself may stay. All other checks passed: check_sanitized.py 14/14, DataTable + worked-example figures (LM=8.42, p=0.015, p 0.03->0.09, weights 1/employees^2) match raw JSON exactly, all 8 Sources curl-verified 2xx with matching titles/content, no cannibalization hit on ''heteroscedasticity test'' in content.db, astro check/tests/build all clean (129 pages, 4880 links, 121 tests, 0 violations).','2026-09-02 19:54:16');
INSERT INTO "outsource_reviews" VALUES(12,'sequential-testing',1,'Round 2: both changes-requested items fixed and independently reverified -- dead Penn State citation replaced with CRAN gsDesign vignette (plain curl -sL, no redirect, 200, live title ''gsDesign package overview'' matches citation exactly; content grep-confirmed covers spending functions/Type I error/O''Brien-Fleming/Pocock; CRAN DESCRIPTION confirms Keaven Anderson authorship) in both the inline citation and Sources list; ''-- Statohub'' sign-off removed, confirmed absent site-wide. Round 1 findings (check_sanitized 14/0, other 6/7 sources, 3 DataTables + 2 infographics, cannibalization, astro check/tests) unchanged and not re-touched by this diff. astro check 0/0/0, 121/121 tests, build 130 pages / 4928 internal links / 0 violations (up from 129/4880 baseline).','2026-09-02 19:57:00');
INSERT INTO "outsource_reviews" VALUES(13,'heteroscedasticity-test',1,'Sign-off line removed as directed; re-verified sanitizer 14/14, sources/table/figures already confirmed round 1, cannibalization clear, build gate clean (131 pages, 4967 links, 121 tests, 0 violations) — publishing.','2026-09-02 19:59:30');
INSERT INTO "outsource_reviews" VALUES(14,'data-visualization-best-practices',0,'Strip vendor sign-off ''> *— Statohub*'' after the Statohub''s Perspective section (present in raw source line 174, absent from every other published outsource article); verify/replace SAGE DOI source (https://doi.org/10.1177/15291006211051956) which returns HTTP 403 Cloudflare bot-challenge on curl -sL (title/authors verified correct via CrossRef metadata, so not a mis-citation, but fails the literal 2xx-status link check).','2026-09-03 18:00:19');
INSERT INTO "outsource_reviews" VALUES(15,'data-visualization-best-practices',1,'Round 2: vendor sign-off confirmed removed cleanly, SAGE DOI replaced with verified Gleicher et al. 2011 (author-hosted PDF, content matches citation and body claim); all 6 Sources resolve 2xx with matching titles (PMC links intermittently bot-walled by NCBI but confirmed genuine on retry); no cannibalization; astro check/tests/build all clean.','2026-09-03 18:21:49');
INSERT INTO "outsource_reviews" VALUES(16,'one-tailed-vs-two-tailed',0,'Strip vendor sign-off line ''> *— Statohub*'' after the Statohub''s Take section (4b vendor template drift, not caught by check_sanitized.py). Remove or re-source the two NIST/SEMATECH Sources entries (itl.nist.gov prc13.htm and eda358.htm) — they resolve fine and titles match, but neither URL nor any NIST reference appears anywhere in raw/one-tailed-vs-two-tailed.json (markdown, html, or any other field); they have no inline citation anchor in the body either, so they cannot be verified against the vendor source and read as fabricated additions.','2026-09-13 14:02:08');
INSERT INTO "outsource_reviews" VALUES(17,'one-tailed-vs-two-tailed',1,'Round 2: vendor sign-off line stripped; NIST top-up sources verified as sanctioned by processor spec Step 3 (backs claims already in text, resolves 200, titles match); sanitizer, fidelity, cannibalization, category, sources, build gate all clean.','2026-09-13 14:04:42');
INSERT INTO "outsource_reviews" VALUES(18,'false-discovery-rate',0,'Vendor ''Statohub''s Take'' section (and follow-on CTA section) entirely dropped, not just the ''> *— Statohub*'' sign-off line per ADR-cited playbook rule 4b; restore the Take section content (minus the sign-off) and the CTA section, keep everything else as-is (sources verified, tables verified against raw, no cannibalization, category correct)','2026-09-13 14:08:37');
INSERT INTO "outsource_reviews" VALUES(19,'false-discovery-rate',0,'Build fails at draft:false: MDX interprets literal ''#{p-values > λ}'' in the ''How to Calculate Q-Values'' section (line ~103, ''The formula is π0(λ) = #{p-values > λ} / (m × (1 − λ)).'') as a JSX/JS expression, throwing ''ReferenceError: p is not defined'' during astro build. Escape or reword the curly braces (e.g. ''#(p-values > λ)'' or escape the braces) so the literal set-notation isn''t parsed as JSX. Everything else in this round cleared: check_sanitized.py (17/17), Take + CTA sections restored correctly (sign-off line stripped, statohub.com links converted to Link components), all 3 DataTables verified against raw, no cannibalization collision, category experiments-causality is a valid Applied hub, all 8 Sources resolve 2xx with matching titles (JSTOR bot-walls confirmed non-issue per round-1 Wayback resolution), no vendor links dropped.','2026-09-13 19:08:11');
INSERT INTO "outsource_reviews" VALUES(20,'false-discovery-rate',1,'Round 3: brace-escape fix on line 103 verified, no other diffs; full gate re-run clean (sanitizer 17/17, tables/sources/backlinks/category/template unchanged from round-2 verification); draft:false build passed astro check, tests, and all build-time gates including db_sync check','2026-09-13 19:11:28');
INSERT INTO "outsource_reviews" VALUES(21,'misleading-graphs',0,'2 mis-cited Sources: NIST link labeled ''Bar Charts'' actually resolves to the generic ''Graphical Techniques: Alphabetic'' index page, not a bar-chart-specific page; Stephen Few PDF cited as ''Are They Ever the Right Solution?'' but actual title is ''Are They Ever the Best Solution?''. Fix citation text or swap in a page/quote that actually matches, then resubmit.','2026-09-13 19:14:22');
INSERT INTO "outsource_reviews" VALUES(22,'misleading-graphs',1,'Round 2: both mis-cited titles corrected (NIST now describes the actual alphabetical-index page; Few now matches the PDF''s real title); all 8 Sources re-verified 2xx with matching titles; sanitizer, fidelity, cannibalization, category, template-drift, and backlinks all clear.','2026-09-13 19:16:30');
INSERT INTO "outsource_reviews" VALUES(23,'cohens-d',1,'check_sanitized 17/17 pass; 3 DataTables + 1 AnnotatedChart verified against raw prose/image; 6 external links + 3 topped-up sources all resolve 200 with matching titles; no cannibalization collision; category data-analysis is Applied hub; sign-off line removed; astro check/test/build clean','2026-09-13 19:30:50');
INSERT INTO "outsource_reviews" VALUES(24,'difference-in-differences',1,'Sanitizer 17/17, tables/infographic verified against raw, all 8 sources resolve 200 with titles matching citations, no keyword collision, draft flipped, build/tests clean.','2026-09-13 19:33:18');
INSERT INTO "outsource_reviews" VALUES(25,'interrupted-time-series',1,'Sanitizer 17/17 pass, table+infographic verified against raw prose numbers, keyword clean, no babylovegrowth links, 8 external sources all resolve (2 known bot-wall exceptions: BMJ 403, Springer Client Challenge, pubmed 203), titles match citations, build/link/meta gates clean','2026-09-13 19:36:28');
INSERT INTO "outsource_reviews" VALUES(26,'communicating-uncertainty',1,'17/17 sanitizer, table/ProcessFlow fidelity verified vs raw, 7/7 partner hrefs preserved, all 6 sources resolve+title-match (pubmed 203 bot-wall sanctioned), no cannibalization, build gates clean','2026-09-13 19:42:23');
INSERT INTO "outsource_reviews" VALUES(27,'conditional-probability-exercises',1,'17/17 sanitizer pass; table/worked-exercise numbers and both infographics verified against raw JSON; 6/6 non-vendor external hrefs present with matching anchor text; 8/8 Sources resolve 200 (Khan Academy is a bot-wall Client Challenge, treated as non-link-rot per session rules) with titles matching citations; no primaryKeyword collision; category data-analysis is a valid Applied hub; vendor sign-off line stripped, Statohub''s Take kept; build/test/astro-check clean.','2026-09-13 19:45:24');
INSERT INTO "outsource_reviews" VALUES(28,'histogram-vs-boxplot',0,'Sources: NIST bin-width citation (https://www.itl.nist.gov/div898/handbook/eda/section3/histbin.htm) 302/301-redirects to generic https://www.nist.gov/itl hub (title ''Information Technology Laboratory | NIST'') -- link rot + mis-citation, replace with a live NIST bin-width page or drop the citation','2026-09-18 12:12:59');
INSERT INTO "outsource_reviews" VALUES(29,'histogram-vs-boxplot',1,'Sources fixed (dead NIST bin-width link dropped, Atlassian source retitled); check_sanitized 17/0, fidelity/cannibalization/build gate all clean','2026-09-18 12:17:43');
INSERT INTO "outsource_reviews" VALUES(30,'multiple-regression-diagnostics',0,'Stray inline body link disguised as ''95%'' anchor text points to an unrelated WMU donation page (give.wmed.edu) instead of a stats citation -- remove/replace it. Two Sources citations (STAT 462 node/131 ''Comparing Regression Models'' and node/180 ''Detecting Multicollinearity Using VIF'', online.stat.psu.edu) fail curl -sL with cert chain error (verify code 21, unable to verify first certificate) -- reproducible link rot/dead-cert host, replace with working PSU stat462 URLs or an alternate source.','2026-09-18 12:21:32');
INSERT INTO "outsource_reviews" VALUES(31,'multiple-regression-diagnostics',1,'Sources fixed (dead PSU STAT462 links replaced with UVA StatLab + statsmodels VIF doc, all 8 resolve 200 with matching titles); give.wmed.edu partner backlink correctly left per ADR 0023; table/infographic fidelity and cannibalization clean; build gate green.','2026-09-18 12:27:01');
INSERT INTO "outsource_reviews" VALUES(32,'missing-data-imputation',1,'Sanitizer clean (17/17); tables/infographics verified against raw JSON; no keyword cannibalization; all 7 Sources resolve 200 with matching titles/content (3 sources beyond vendor''s own Sources list added, but 2 match in-body links and the 3rd — JStatSoft mice paper — verified accurate to MICE content discussed); category=data-analysis (valid Applied hub); vendor sign-off line stripped; build gate clean.','2026-09-18 12:31:22');
INSERT INTO "outsource_reviews" VALUES(33,'box-plot-interpretation',0,'Strip vendor sign-off line ''> *— Statohub*'' after the ''Why Statohub Treats...'' section (template drift, not caught by check_sanitized.py). Fix Minitab Sources citation: URL https://support.minitab.com/en-us/engage/help-and-how-to/tools/forms/types-of-forms/statistical-analysis/graph-your-data/ resolves 200 but its live title/H1 is ''Graph Your Data - Minitab Engage'', not ''Interpret the key results for Boxplot'' as cited -- retitle the citation to match the actual page or source the correct Minitab ''Interpret the key results for Boxplot'' URL.','2026-09-19 18:10:41');
INSERT INTO "outsource_reviews" VALUES(34,'box-plot-interpretation',1,'Round 2: sign-off line stripped, Minitab citation re-pointed to correct ''Interpret the key results for Boxplot'' page (title verified match); sanitizer, source links, table fidelity, cannibalization, and build gate all clean.','2026-09-19 18:14:08');
CREATE INDEX idx_outsource_status ON outsource_articles(status);
CREATE INDEX idx_outsource_queue ON outsource_articles(queue_position);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('outsource_reviews',34);
COMMIT;
