BEGIN TRANSACTION;
CREATE TABLE articles (
  slug             TEXT PRIMARY KEY,           -- flat URL slug (primary keyword only, no category in path)
  title            TEXT NOT NULL,
  category_slug    TEXT NOT NULL REFERENCES categories(slug),
  primary_keyword  TEXT NOT NULL,
  phase            INTEGER,                    -- 1 | 2 | 3 | NULL (stub, pending research)
  kd_min           INTEGER,
  kd_max           INTEGER,
  combined_volume  INTEGER,                    -- study "Combined US/mo" ceiling
  embed_calculator TEXT REFERENCES calculators(slug),  -- the <StatCalc> embedded in the article (NULL = concept-only)
  standalone_calc  INTEGER NOT NULL DEFAULT 0, -- 1 = this topic also ships a standalone /calculators/ page
  status           TEXT NOT NULL DEFAULT 'planned',
                   -- planned -> briefed -> drafting -> in_review -> changes_requested -> approved -> published
                   -- (changes_requested loops back to drafting; research_pending = stub, not writable yet)
  review_score     INTEGER,                    -- latest reviewer score (0-100)
  word_count       INTEGER,
  flagged          INTEGER NOT NULL DEFAULT 0, -- 1 = intent/thin flag from the study; surfaces but don't write blind
  notes            TEXT NOT NULL DEFAULT '',
  mdx_path         TEXT,                        -- src/content/articles/{slug}.mdx once drafted
  pub_date         TEXT,
  updated_at       TEXT NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO "articles" VALUES('how-to-find-the-mean','How to Find the Mean (Average): Formula & Steps','descriptive-statistics','how to find the mean',1,9,22,195000,'mean',0,'published',90,NULL,0,'',NULL,NULL,'2026-06-30 01:10:33');
INSERT INTO "articles" VALUES('what-is-an-average','What Is an Average? Mean Definition, Types & Meaning','descriptive-statistics','what is the average',1,0,34,124000,'mean',0,'published',90,NULL,0,'''distribution mean'' moved to PD2 (dedup).',NULL,NULL,'2026-06-18 01:09:48');
INSERT INTO "articles" VALUES('mean-vs-average','Mean vs Average - Are They the Same Thing?','descriptive-statistics','mean vs average',1,1,26,70500,'mean',0,'published',90,NULL,0,'',NULL,NULL,'2026-06-23 21:54:33');
INSERT INTO "articles" VALUES('weighted-average','Weighted Average: Formula & Calculator','descriptive-statistics','weighted average',1,0,21,93400,'weighted-average',1,'published',90,NULL,0,'',NULL,NULL,'2026-06-20 21:57:01');
INSERT INTO "articles" VALUES('how-to-find-the-median','How to Find the Median: Formula & Steps','descriptive-statistics','how to find the median',3,26,33,122200,'median',0,'published',90,NULL,0,'',NULL,NULL,'2026-07-07 01:18:02');
INSERT INTO "articles" VALUES('median-vs-average','Median vs Average & What "Median" Means','descriptive-statistics','median vs average',1,2,48,77500,'median',0,'published',90,NULL,0,'',NULL,NULL,'2026-06-24 21:53:02');
INSERT INTO "articles" VALUES('mean-median-mode-range','Mean, Median, Mode & Range: The Complete Guide','descriptive-statistics','mean median mode range',2,1,37,94700,'mean-median-mode-range',0,'published',90,NULL,0,'',NULL,NULL,'2026-07-01 21:52:16');
INSERT INTO "articles" VALUES('standard-deviation','Standard Deviation: Meaning, Formula & How to Calculate','descriptive-statistics','standard deviation',3,21,56,384500,'standard-deviation',1,'published',90,NULL,0,'Category pillar / head term. An MDX stub already exists.',NULL,NULL,'2026-07-06 01:14:58');
INSERT INTO "articles" VALUES('standard-deviation-symbol','The Standard Deviation Symbol (Sigma): Signs & Notation','descriptive-statistics','standard deviation symbol',1,0,13,187500,'standard-deviation',0,'published',96,NULL,0,'Big low-KD win.',NULL,NULL,'2026-06-14 17:25:30');
INSERT INTO "articles" VALUES('standard-deviation-excel','How to Calculate Standard Deviation in Excel','descriptive-statistics','standard deviation excel',1,0,6,54000,'standard-deviation',0,'published',90,NULL,0,'',NULL,NULL,'2026-06-23 01:10:53');
INSERT INTO "articles" VALUES('variance','Variance: Definition, Formula & vs Standard Deviation','descriptive-statistics','variance',1,14,45,157700,'variance',1,'published',90,NULL,0,'',NULL,NULL,'2026-06-30 21:54:30');
INSERT INTO "articles" VALUES('sample-variance-formula','Sample Variance Formula Explained','descriptive-statistics','sample variance formula',2,14,35,48600,'variance',0,'published',90,NULL,0,'',NULL,NULL,'2026-07-04 01:15:40');
INSERT INTO "articles" VALUES('mean-absolute-deviation','Mean Absolute Deviation & Coefficient of Variation','descriptive-statistics','mean absolute deviation',1,0,19,105900,'mean-absolute-deviation',1,'published',90,NULL,0,'',NULL,NULL,'2026-06-19 01:11:35');
INSERT INTO "articles" VALUES('how-to-find-the-range','How to Find the Range in Statistics','descriptive-statistics','how to find the range',1,0,19,161760,'range-iqr',0,'published',90,NULL,0,'2026-07-11: absorbed 5 keywords from the retired range-of-a-function-statistics stub (exact-match DataForSEO pull, see 22-wrongintent-reseed-keyword-research.md) -- that stub''s algebra intent was dropped, its clean statistics-range keywords folded in here instead of shipping a separate page. Stretch keyword ''range statistics'' (2,900 vol, KD 25, mixed SERP) deliberately left out -- optional add later. Article is already published; this keyword addition needs a light content refresh pass to actually work the new phrases into the live page, not just the DB.',NULL,NULL,'2026-06-15 18:56:08');
INSERT INTO "articles" VALUES('how-to-find-outliers','How to Find Outliers: The 1.5xIQR Rule & Formula','descriptive-statistics','how to find outliers',1,6,14,40500,'outlier',0,'published',90,NULL,0,'',NULL,NULL,'2026-06-28 21:52:55');
INSERT INTO "articles" VALUES('interquartile-range','Interquartile Range (IQR): Formula & How to Find It','descriptive-statistics','interquartile range',1,8,22,102900,'range-iqr',0,'published',90,NULL,0,'',NULL,NULL,'2026-06-29 21:54:15');
INSERT INTO "articles" VALUES('percentiles','Percentiles: Meaning, Definition & How to Calculate','descriptive-statistics','percentile meaning',1,7,22,56100,'percentile',1,'published',90,NULL,0,'',NULL,NULL,'2026-06-29 01:11:53');
INSERT INTO "articles" VALUES('frequency-table','Frequency Tables: How to Build & Read Them','descriptive-statistics','frequency table',1,0,20,59800,'frequency-table',1,'published',90,NULL,0,'Frequency silo pillar, KD 1 - build early.',NULL,NULL,'2026-06-22 21:55:26');
INSERT INTO "articles" VALUES('probability-formula','Probability: Formula, Conditional Probability & Expected Value','probability-distributions','probability formula',1,4,31,66000,'probability',1,'published',90,NULL,0,'Consolidated probability pillar; probability side is keyword-thin (dedicated research candidate).',NULL,NULL,'2026-06-26 01:07:08');
INSERT INTO "articles" VALUES('probability-distribution','Probability Distributions Explained: Types, Mean & Examples','probability-distributions','probability distribution',1,0,24,64000,NULL,0,'published',90,NULL,0,'Overview/hub; owns ''distribution mean'' (moved from A2).',NULL,NULL,'2026-06-22 02:27:08');
INSERT INTO "articles" VALUES('normal-distribution','Normal Distribution: The Bell Curve Explained','probability-distributions','normal distribution',3,20,40,95200,'normal-distribution',1,'published',90,NULL,0,'Head pillar; ''standard gaussian distribution'' relocated in from Stage 5.',NULL,NULL,'2026-07-05 21:52:04');
INSERT INTO "articles" VALUES('z-table','Z-Table: The Standard Normal Distribution Table (How to Read It)','probability-distributions','z score table',1,2,20,140000,'z-table',1,'published',90,NULL,0,'Biggest low-KD win in the category. z-table lookup (vs z-score on I1).',NULL,NULL,'2026-06-24 01:11:34');
INSERT INTO "articles" VALUES('binomial-distribution','Binomial Distribution: Formula, Examples & How to Use It','probability-distributions','binomial distribution',2,8,35,64300,'binomial-distribution',1,'published',90,NULL,0,'',NULL,NULL,'2026-07-02 21:53:09');
INSERT INTO "articles" VALUES('skewed-distribution','Skewed Distributions: Left Skew, Right Skew & Distribution Shape','probability-distributions','left skewed distribution',1,0,16,92600,NULL,0,'published',90,NULL,0,'Very low KD, diagram-led.',NULL,NULL,'2026-06-21 01:09:11');
INSERT INTO "articles" VALUES('exponential-distribution','Continuous Distributions: Exponential, Uniform, Gamma & Lognormal','probability-distributions','exponential distribution',2,8,28,64300,NULL,0,'published',90,NULL,0,'',NULL,NULL,'2026-07-03 01:14:17');
INSERT INTO "articles" VALUES('permutations-and-combinations','Permutations vs. Combinations: What''s the Difference?','combinatorics','permutations and combinations',55,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #16/H01). Graduated from research_pending stub: confirmed zero-volume structural hub by design (file 18 sec4), not a research gap anymore. Must link down to all 4 spokes: fundamental-counting-principle, permutations, combinations, binomial-theorem.',NULL,NULL,'2026-07-31 01:20:11');
INSERT INTO "articles" VALUES('correlation-coefficient','Correlation Coefficient (r): Formula & How to Interpret r Values','regression-correlation','correlation coefficient',2,0,34,168000,'correlation-coefficient',1,'published',90,NULL,0,'Category pillar; absorbs the KD-0 r-value interpretation quizzes.',NULL,NULL,'2026-07-01 01:11:07');
INSERT INTO "articles" VALUES('pearson-correlation-coefficient','Pearson Correlation Coefficient: Formula, Covariance & Spearman','regression-correlation','pearson correlation',2,13,36,83300,'correlation-coefficient',0,'published',90,NULL,0,'Shares the RC1 correlation tool.',NULL,NULL,'2026-07-03 21:51:37');
INSERT INTO "articles" VALUES('what-is-correlation','What Is Correlation? Definition, Positive vs Negative & Types','regression-correlation','correlation definition',1,0,29,78700,NULL,0,'published',90,NULL,0,'Plain-language entry; scatter-plot demo (not a calc embed).',NULL,NULL,'2026-06-21 21:57:22');
INSERT INTO "articles" VALUES('correlation-vs-causation','Correlation vs Causation: Why Correlation Doesn''t Imply Causation','regression-correlation','correlation vs causation',1,0,23,136900,NULL,0,'published',90,NULL,0,'Phase-1 mega-win: ''which correlation is most likely a causation'' 49.5k/KD0.',NULL,NULL,'2026-06-17 21:52:49');
INSERT INTO "articles" VALUES('linear-regression','Linear Regression: Equation, Formula & How It Works','regression-correlation','linear regression',1,0,47,117200,'linear-regression',1,'published',90,NULL,0,'Head term KD47 with KD-0/KD-9 easy entries; logistic regression folded in.',NULL,NULL,'2026-06-18 21:55:12');
INSERT INTO "articles" VALUES('regression-to-the-mean','Regression to the Mean: Definition & Real-World Examples','regression-correlation','regression to the mean',2,12,25,32400,NULL,0,'published',90,NULL,0,'FLAGGED thin (4 KWs). Recommend standalone (distinct intent from regression analysis). Unflagged 2026-07-11: no keyword/intent issue found, cleared for publishing as-is.',NULL,NULL,'2026-07-14 01:20:08');
INSERT INTO "articles" VALUES('z-score','Z-Score: Formula, How to Calculate & What It Means','inferential-statistics','z score',1,3,41,127700,'z-score',1,'published',90,NULL,0,'z-score (statistic); z-table lookup lives on PD4.',NULL,NULL,'2026-06-25 01:10:16');
INSERT INTO "articles" VALUES('p-value','P-Value: What It Is & How to Calculate It','inferential-statistics','p value',2,16,30,66700,'p-value',1,'published',90,NULL,0,'',NULL,NULL,'2026-07-04 21:50:45');
INSERT INTO "articles" VALUES('null-hypothesis','Null Hypothesis: Definition, Examples & How to State It','inferential-statistics','what is a null hypothesis',1,3,22,89900,NULL,0,'published',90,NULL,1,'FLAGGED intent caution: the four ''what does null mean'' variants are ambiguous (programming null). Lead with stats framing + disambiguation line.',NULL,NULL,'2026-07-08 01:17:56');
INSERT INTO "articles" VALUES('test-statistic','Test Statistic: Formula, Critical Values, Degrees of Freedom & the t-Table','inferential-statistics','test statistic',1,3,24,56700,'t-table',1,'published',90,NULL,0,'Dense Phase-1 cluster; 3 df-definitional variants relocated in from Stage 5.',NULL,NULL,'2026-06-25 21:54:29');
INSERT INTO "articles" VALUES('t-test','T-Test: Formula, Paired & Two-Sample T-Tests Explained','inferential-statistics','paired t-test',2,2,20,69600,'t-test',1,'published',90,NULL,0,'Mann-Whitney lives on I9, not here. Comparison phrasings (''t-test and paired t-test'' / ''t test and paired t test'') reassigned to paired-vs-independent-t-test per Phase-2 brief T16 routing guard.',NULL,NULL,'2026-07-02 01:19:09');
INSERT INTO "articles" VALUES('chi-square-test','Chi-Square Test: Formula, Equation & How to Use It','inferential-statistics','chi square test',3,27,34,187300,'chi-square',1,'published',90,NULL,0,'All spelling variants consolidated; distribution side -> I7.',NULL,NULL,'2026-07-07 21:54:52');
INSERT INTO "articles" VALUES('chi-square-distribution','Chi-Square Distribution: Shape, Table & Probability Density','inferential-statistics','chi square distribution',2,18,36,92900,NULL,0,'published',90,NULL,0,'Shares I6 chi-square engine; distribution/table half.',NULL,NULL,'2026-07-05 01:17:16');
INSERT INTO "articles" VALUES('confidence-interval','Confidence Interval: Formula & How to Calculate a 95% CI','inferential-statistics','confidence interval formula',2,20,24,28000,'confidence-interval',1,'published',90,NULL,0,'FLAGGED thin (3 KWs). Rich topic; flag for a dedicated KW pass (margin of error, confidence level, sample size). Unflagged 2026-07-11: no keyword/intent issue found, cleared for publishing as-is.',NULL,NULL,'2026-07-15 01:14:42');
INSERT INTO "articles" VALUES('fundamental-statistics','Fundamental Statistics: What Statistics Is & Why It Matters','statistics-basics','fundamental statistics',1,1,50,407500,NULL,0,'published',90,NULL,0,'Flagship ''2nd homepage'' (fundamental statistics 301k/KD7). Links out to every category.',NULL,NULL,'2026-06-23 19:38:08');
INSERT INTO "articles" VALUES('parameter-vs-statistic','Parameter vs Statistic: Definitions, Symbols & How to Tell Them Apart','statistics-basics','parameter vs statistics',1,0,8,103400,NULL,0,'published',90,NULL,0,'Clean KD 0-8 sweep of nine variants.',NULL,NULL,'2026-06-19 21:55:43');
INSERT INTO "articles" VALUES('proportions-in-statistics','Proportions in Statistics: Meaning, Formula & How to Solve Them','statistics-basics','proportion in statistics',1,0,13,7320,'proportion',1,'published',90,NULL,0,'2026-07-11: fresh exact-match keyword research complete (22-wrongintent-reseed-keyword-research.md), replacing the 2026-07-11 re-scope''s placeholder list. Primary swapped to "proportion in statistics" (880 vol, KD 3); old primary "proportion means in statistics" dropped -- confirmed null/no-volume in the exact-match pull. sample proportion (1,600) and population proportion (1,000) are distinct inferential-stats concepts folded into this hub for now; could split into their own pages later if the board wants more depth.',NULL,NULL,'2026-07-12 01:18:31');
INSERT INTO "articles" VALUES('validity-in-statistics','Validity in Research: Construct, Internal & External Validity Explained','statistics-basics','construct validity statistics',NULL,6,11,16500,NULL,0,'research_pending',NULL,NULL,1,'STUB / research_pending: only 2 KWs. Do NOT build until a research-methods keyword pass (validity types, reliability, bias, design) expands it.',NULL,NULL,'2026-06-14 12:52:26');
INSERT INTO "articles" VALUES('types-of-variables','Types of Variables: Qualitative vs. Quantitative','statistics-basics','qualitative vs quantitative',40,5,29,78400,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #1/B07). Highest single-keyword volume in the study batch. Do not re-attach Mann-Whitney/Kruskal-Wallis phrasings (reassigned to T14/T15).',NULL,NULL,'2026-07-16 01:22:04');
INSERT INTO "articles" VALUES('binomial-theorem','Binomial Theorem & Binomial Coefficient Explained','combinatorics','binomial theorem',41,17,22,107100,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #2/T22). Reassigned from B03 pull. Must disambiguate vs binomial-distribution (do not merge). Links to /combinations/ (required guard).',NULL,NULL,'2026-07-17 01:17:03');
INSERT INTO "articles" VALUES('central-limit-theorem','Central Limit Theorem: Definition & Examples','probability-distributions','central limit theorem',42,15,15,33100,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #3/T08). Single strong head term, no supporting long-tail found after two research rounds.',NULL,NULL,'2026-07-18 01:18:46');
INSERT INTO "articles" VALUES('permutations','Permutations: Formula & Examples','combinatorics','permutation',43,25,39,39200,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #4/T20). No ''with/without repetition'' split (zero volume, locked decision). Required cross-links: T19, T21, H01, /combinatorics/.',NULL,NULL,'2026-07-19 01:21:37');
INSERT INTO "articles" VALUES('combinations','Combinations: Formula & Examples','combinatorics','combination formula',44,15,15,18100,'combination',1,'published',90,NULL,0,'Phase-2 batch (brief #5/T21). Only confirmed term is ''combination formula''. Required cross-links: T19, T20, H01, /combinatorics/.',NULL,NULL,'2026-07-20 01:19:47');
INSERT INTO "articles" VALUES('type-i-and-type-ii-errors','Type I and Type II Errors Explained','inferential-statistics','type i and type ii errors',45,6,10,34700,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #6/T04).',NULL,NULL,'2026-07-21 01:18:53');
INSERT INTO "articles" VALUES('bayes-theorem','Bayes'' Theorem (Bayes'' Rule): Formula & Examples','probability-distributions','bayes rule',46,23,24,26900,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #7/T18). Do not target ''bayesian statistics'' or ''conditional probability formula'' (owned by probability-distribution / probability-formula). No third re-seed recommended.',NULL,NULL,'2026-07-22 01:17:31');
INSERT INTO "articles" VALUES('levels-of-measurement','Levels of Measurement: Nominal, Ordinal, Interval & Ratio','statistics-basics','ordinal variable vs nominal',47,13,19,16500,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #8/T13). Strongest topic in the batch by keyword count; cluster of ~13 ''nominal ordinal interval ratio'' variants at ~6600/KD19-34, only one example figure confirmed -- do not invent the rest.',NULL,NULL,'2026-07-23 01:22:16');
INSERT INTO "articles" VALUES('mann-whitney-u-test','Mann-Whitney U Test: Formula & When to Use It','inferential-statistics','mann-whitney t-test',48,7,14,25600,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #9/T14). Reassigned from T11/T17/B07 leaks. Splits the retired ''non-parametric-tests'' stub together with T15 -- do not link a non-parametric-tests page. Required cross-link: /kruskal-wallis-test/.',NULL,NULL,'2026-07-24 01:24:20');
INSERT INTO "articles" VALUES('r-squared-adjusted-r-squared','R-Squared & Adjusted R-Squared Explained','regression-correlation','coefficient of determination',49,19,19,9900,'linear-regression',1,'changes_requested',50,NULL,0,'Phase-2 batch (brief #10/B06). Zero signal for bare ''r-squared''/''adjusted r-squared'' in both research rounds -- SEO emphasis should prioritize ''coefficient of determination'', title keeps ''R-Squared'' for readability.',NULL,NULL,'2026-07-25 01:22:55');
INSERT INTO "articles" VALUES('reliability-cronbachs-alpha-cohens-kappa','Reliability in Statistics: Cronbach''s Alpha & Cohen''s Kappa','statistics-basics','cronbach''s alpha',50,10,20,22000,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #11/B05). Two distinct subtopics (internal consistency vs inter-rater agreement) -- keep clearly separated, do not blend formulas. Companion to validity-in-statistics stub.',NULL,NULL,'2026-07-26 01:19:29');
INSERT INTO "articles" VALUES('effect-size','Effect Size: What It Means & How to Interpret It','inferential-statistics','effect size',51,18,28,24300,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #12/T06). Keyword set fixed on re-seed -- use only these three figures.',NULL,NULL,'2026-07-27 01:19:03');
INSERT INTO "articles" VALUES('kruskal-wallis-test','Kruskal-Wallis Test: Formula & When to Use It','inferential-statistics','kruskal-wallis analysis of variance',52,5,8,19800,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #13/T15). Reassigned from B07 leak. Splits the retired ''non-parametric-tests'' stub together with T14. Required cross-links: /one-way-anova/, /mann-whitney-u-test/. Despite ''analysis of variance'' in the phrase, do NOT let it bleed into one-way-anova content.',NULL,NULL,'2026-07-28 01:18:03');
INSERT INTO "articles" VALUES('paired-vs-independent-t-test','Paired vs. Independent T-Test: Which One Do You Need?','inferential-statistics','t-test and paired t-test',53,0,9,18500,'t-test',1,'published',90,NULL,0,'Phase-2 batch (brief #14/T16). Do not target bare ''paired t-test'' (belongs to the existing planned t-test article).',NULL,NULL,'2026-07-29 01:19:56');
INSERT INTO "articles" VALUES('empirical-rule','The Empirical Rule (68-95-99.7 Rule) Explained','descriptive-statistics','empirical rule statistics',54,11,11,4400,'normal-distribution',1,'published',90,NULL,0,'Phase-2 batch (brief #15/B01). Thinnest keyword-validated topic in the batch -- single confirmed term, do not pad. Required link: normal-distribution.',NULL,NULL,'2026-07-30 01:18:23');
INSERT INTO "articles" VALUES('fundamental-counting-principle','The Fundamental Counting Principle Explained','combinatorics','fundamental counting principle',56,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #17/T19). Topical-authority write, no confirmed keyword data. Cluster''s conceptual prerequisite -- links up to H01 and forward to permutations/combinations.',NULL,NULL,'2026-08-01 01:20:22');
INSERT INTO "articles" VALUES('one-way-anova','One-Way ANOVA: When and How to Use It','inferential-statistics','one way anova',57,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #18/T01). Zero keyword signal across two seeding rounds (T01/T02/T03/T05 group). Required: cross-link to kruskal-wallis-test as non-parametric analogue; do not use ''kruskal wallis analysis of variance'' phrasing here.',NULL,NULL,'2026-08-02 01:18:39');
INSERT INTO "articles" VALUES('two-way-anova','Two-Way ANOVA: Testing Multiple Factors','inferential-statistics','two way anova',58,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #19/T02). Zero keyword signal (T01/T02/T03/T05 group).',NULL,NULL,'2026-08-03 01:19:07');
INSERT INTO "articles" VALUES('post-hoc-tests','Post-Hoc Tests: Tukey, Bonferroni & When to Use Them','inferential-statistics','post hoc tests',59,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #20/T03). Zero keyword signal (T01/T02/T03/T05 group). Frame as the necessary follow-up to a significant ANOVA, not a standalone alternative.',NULL,NULL,'2026-08-04 01:20:54');
INSERT INTO "articles" VALUES('statistical-power','Statistical Power: What It Means and How to Calculate It','inferential-statistics','statistical power',60,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #21/T05). Zero keyword signal (T01/T02/T03/T05 group).',NULL,NULL,'2026-08-05 01:22:59');
INSERT INTO "articles" VALUES('which-statistical-test-should-i-use','Which Statistical Test Should You Use? A Decision Guide','inferential-statistics','which statistical test should i use',61,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #22/B08). Structural wayfinding page, no cannibalization risk. Should link to every named test article once they exist.',NULL,NULL,'2026-08-06 01:22:05');
INSERT INTO "articles" VALUES('f-test-f-distribution','F-Test and F-Distribution Explained','probability-distributions','f test f distribution',62,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #23/T07). Scope narrowed to F-test/F-distribution only -- chi-square-distribution and t-distribution content stays out (hard scope guard).',NULL,NULL,'2026-08-07 01:23:07');
INSERT INTO "articles" VALUES('sampling-distributions','Sampling Distributions: What They Are and Why They Matter','probability-distributions','sampling distributions',63,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #24/T09). Scoped to sampling distribution of the mean/proportion only -- general population-distribution content belongs to the published probability-distribution article (hard guard). Do not use chi-square-distribution phrasings.',NULL,NULL,'2026-08-08 01:20:34');
INSERT INTO "articles" VALUES('poisson-distribution','Poisson Distribution: Formula & Examples','probability-distributions','poisson distribution',64,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #25/T10). No confirmed keyword data. Brief names a Poisson calculator embed (suite 6) but no ''poisson'' slug exists in calculators yet -- flag as a build gap before assuming an embed.',NULL,NULL,'2026-08-09 01:19:33');
INSERT INTO "articles" VALUES('independent-dependent-mutually-exclusive-events','Independent, Dependent & Mutually Exclusive Events','probability-distributions','independent dependent mutually exclusive events',65,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #26/B02). Core teaching point: mutually exclusive is NOT the same as independent (must stay explicit).',NULL,NULL,'2026-08-10 01:21:32');
INSERT INTO "articles" VALUES('hypergeometric-distribution','Hypergeometric Distribution: Formula & Examples','probability-distributions','hypergeometric distribution',66,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #27/B03). Do not re-attach ''binomial theorem''/''pascal''s triangle'' keywords (reassigned to T22).',NULL,NULL,'2026-08-11 01:18:55');
INSERT INTO "articles" VALUES('regression-assumptions','Linear Regression Assumptions Explained','regression-correlation','linear regression assumptions',67,NULL,NULL,NULL,'linear-regression',1,'published',90,NULL,0,'Phase-2 batch (brief #28/T11). Multicollinearity subsection should hand off to multicollinearity-vif, not duplicate it.',NULL,NULL,'2026-08-12 01:24:06');
INSERT INTO "articles" VALUES('multicollinearity-vif','Multicollinearity & Variance Inflation Factor (VIF) Explained','regression-correlation','multicollinearity variance inflation factor',68,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #29/T12). Do not assume a VIF calculator exists -- suite 7 is documented as simple/bivariate only.',NULL,NULL,'2026-08-13 01:23:16');
INSERT INTO "articles" VALUES('simpsons-paradox','Simpson''s Paradox: What It Is and Why It Happens','regression-correlation','simpson''s paradox',69,NULL,NULL,NULL,NULL,0,'published',90,NULL,0,'Phase-2 batch (brief #30/B04). Two independent seed rounds returned only noise (TV-show contamination) -- no real keyword data, do not fabricate figures. Companion to correlation-vs-causation.',NULL,NULL,'2026-08-14 01:26:25');
INSERT INTO "articles" VALUES('how-to-find-frequency-statistics','How to Find Frequency in Statistics','descriptive-statistics','frequency in statistics',1,0,15,4700,NULL,0,'published',90,NULL,0,'2026-07-11: fresh exact-match keyword research complete (22-wrongintent-reseed-keyword-research.md), replacing the physics-drifted list from the 2026-07-11 re-scope. Primary swapped to "frequency in statistics" (1,000 vol, KD 15). High-volume near-zero-KD split candidates (frequency table 22,200/KD1, relative frequency 18,100/KD2, frequency distribution 8,100/KD20, cumulative frequency 5,400/KD0, frequency polygon 5,400/KD0) were checked against seed.json: frequency table and frequency distribution/polygon/relative-frequency-table are already covered by the published frequency-table article; relative frequency and cumulative frequency as standalone primaries are NOT yet covered and are a candidate for future new articles -- flagged for a board decision, not created here.',NULL,NULL,'2026-07-13 01:18:54');
INSERT INTO "articles" VALUES('statistics-symbols-cheatsheet','Statistics Symbols Cheat Sheet','statistics-basics','statistics symbols cheat sheet',1,0,1,28000,NULL,0,'published',90,NULL,0,'FLAGGED thin (3 KWs) but KD 0-1. Home for the ~40-entry symbol glossary - substance is fine. Unflagged + rebranded 2026-07-11: reframed as a "cheat sheet" reference page, slug/title updated to match; underlying keywords were already statistics-scoped so KD/volume left as-is.',NULL,NULL,'2026-07-11 15:51:23');
INSERT INTO "articles" VALUES('data-drift-detection','Data Drift Detection: A Practical Guide for Production ML Systems','machine-learning-statistics','data drift detection',70,NULL,NULL,NULL,NULL,0,'published',NULL,NULL,1,'Applied batch 1 (phase 70). Gold-standard demo article named in the applied style plan sec.8. Flagged so the nightly cloud routine cannot auto-publish it; published manually 2026-08-16.',NULL,NULL,'2026-08-16 14:32:17');
INSERT INTO "articles" VALUES('how-to-design-an-ab-test','How to Design an A/B Test That Answers Your Question','experiments-causality','a/b test design',70,NULL,NULL,NULL,NULL,0,'published',NULL,NULL,1,'Applied batch 1 (phase 70). Flagged so the nightly cloud routine cannot auto-publish it; published manually 2026-08-16.',NULL,NULL,'2026-08-16 14:32:18');
INSERT INTO "articles" VALUES('exploratory-data-analysis','Exploratory Data Analysis: A Practical Workflow','data-analysis','exploratory data analysis',70,NULL,NULL,NULL,NULL,0,'published',NULL,NULL,1,'Applied batch 1 (phase 70). Flagged so the nightly cloud routine cannot auto-publish it; published manually 2026-08-16.',NULL,NULL,'2026-08-16 14:32:18');
INSERT INTO "articles" VALUES('forecast-accuracy-metrics','Forecast Accuracy Metrics: MAE, RMSE, MAPE and When Each Misleads','time-series-forecasting','forecast accuracy metrics',70,NULL,NULL,NULL,NULL,0,'published',NULL,NULL,1,'Applied batch 1 (phase 70). Flagged so the nightly cloud routine cannot auto-publish it; published manually 2026-08-16.',NULL,NULL,'2026-08-16 14:32:18');
CREATE TABLE calculators (
  slug          TEXT PRIMARY KEY,
  title         TEXT NOT NULL,
  engine        TEXT NOT NULL DEFAULT '',
  standalone    INTEGER NOT NULL DEFAULT 1,   -- 1 = has its own /calculators/{slug}/ page; 0 = embed-only
  category_slug TEXT REFERENCES categories(slug),
  tool_keyword  TEXT,                          -- the tool-intent keyword (standalone pages only; NULL = embed/widget only)
  kd            INTEGER,
  volume        INTEGER,
  phase         INTEGER
);
INSERT INTO "calculators" VALUES('mean','Mean Calculator','mean',1,'descriptive-statistics','mean calculator',6,27100,1);
INSERT INTO "calculators" VALUES('average','Average Calculator','mean',1,'descriptive-statistics','average calculator',25,74000,2);
INSERT INTO "calculators" VALUES('weighted-average','Weighted Average Calculator','weighted-average',1,'descriptive-statistics','weighted average calculator',14,12100,1);
INSERT INTO "calculators" VALUES('median','Median Calculator','median',0,'descriptive-statistics',NULL,NULL,NULL,NULL);
INSERT INTO "calculators" VALUES('mean-median-mode-range','Mean, Median, Mode & Range Calculator','mmmr',0,'descriptive-statistics',NULL,NULL,NULL,NULL);
INSERT INTO "calculators" VALUES('standard-deviation','Standard Deviation Calculator','standard-deviation',1,'descriptive-statistics','standard deviation calculator',34,74000,3);
INSERT INTO "calculators" VALUES('variance','Variance Calculator','variance',1,'descriptive-statistics','variance calculator',10,6600,1);
INSERT INTO "calculators" VALUES('mean-absolute-deviation','Mean Absolute Deviation Calculator','mad',1,'descriptive-statistics','mean absolute deviation calculator',0,6600,1);
INSERT INTO "calculators" VALUES('range-iqr','Range / IQR Calculator','range-iqr',0,'descriptive-statistics',NULL,NULL,NULL,NULL);
INSERT INTO "calculators" VALUES('outlier','Outlier (1.5xIQR) Calculator','outlier',0,'descriptive-statistics',NULL,NULL,NULL,NULL);
INSERT INTO "calculators" VALUES('percentile','Percentile Calculator','percentile',1,'descriptive-statistics','percentile calculator',21,9900,2);
INSERT INTO "calculators" VALUES('frequency-table','Frequency Distribution Table Generator','frequency-table',1,'descriptive-statistics',NULL,NULL,NULL,1);
INSERT INTO "calculators" VALUES('probability','Probability Calculator','probability',1,'probability-distributions','probability calculator',0,12100,1);
INSERT INTO "calculators" VALUES('normal-distribution','Normal Distribution Calculator','normal-distribution',1,'probability-distributions','normal distribution calculator',19,8100,2);
INSERT INTO "calculators" VALUES('z-table','Z-Table Lookup','z-table',1,'probability-distributions',NULL,NULL,NULL,1);
INSERT INTO "calculators" VALUES('binomial-distribution','Binomial Distribution Calculator','binomial',1,'probability-distributions','binomial distribution calculator',5,8100,1);
INSERT INTO "calculators" VALUES('factorial','Factorial Calculator','factorial',1,'combinatorics','factorial calculator',0,6600,1);
INSERT INTO "calculators" VALUES('combination','Combination Calculator','combination',1,'combinatorics','combination calculator',15,6600,2);
INSERT INTO "calculators" VALUES('correlation-coefficient','Correlation Coefficient Calculator','correlation',1,'regression-correlation','correlation coefficient calculator',11,8100,2);
INSERT INTO "calculators" VALUES('linear-regression','Linear Regression Calculator','linear-regression',1,'regression-correlation','linear regression calculator',5,6600,1);
INSERT INTO "calculators" VALUES('z-score','Z-Score Calculator','z-score',1,'inferential-statistics','z score calculator',8,12100,1);
INSERT INTO "calculators" VALUES('p-value','P-Value Calculator','p-value',1,'inferential-statistics','p value calculator',25,8100,2);
INSERT INTO "calculators" VALUES('t-test','T-Test Calculator','t-test',1,'inferential-statistics','t-test calculator',13,6600,2);
INSERT INTO "calculators" VALUES('chi-square','Chi-Square Calculator','chi-square',1,'inferential-statistics','chi square calculator',7,6600,1);
INSERT INTO "calculators" VALUES('sample-size','Sample Size Calculator','sample-size',1,'inferential-statistics','sample size calculator',40,8100,3);
INSERT INTO "calculators" VALUES('t-table','T-Distribution Table Lookup','t-table',1,'inferential-statistics',NULL,NULL,NULL,1);
INSERT INTO "calculators" VALUES('confidence-interval','Confidence Interval Calculator','confidence-interval',1,'inferential-statistics',NULL,NULL,NULL,2);
INSERT INTO "calculators" VALUES('proportion','Proportion Calculator','proportion',1,'statistics-basics','proportion calculator',16,14800,2);
CREATE TABLE categories (
  slug        TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  nav_order   INTEGER NOT NULL DEFAULT 0
, section TEXT NOT NULL DEFAULT 'learn');
INSERT INTO "categories" VALUES('descriptive-statistics','Descriptive Statistics','Core summaries for describing datasets: center, spread, and shape.',1,'learn');
INSERT INTO "categories" VALUES('probability-distributions','Probability & Distributions','The rules of chance and the named distributions they generate.',2,'learn');
INSERT INTO "categories" VALUES('regression-correlation','Regression & Correlation','Relationships between variables: correlation, causation, and regression.',3,'learn');
INSERT INTO "categories" VALUES('combinatorics','Combinatorics','Counting, permutations, combinations, and factorials.',4,'learn');
INSERT INTO "categories" VALUES('statistics-basics','Foundations Hub','What statistics is, notation, parameters vs statistics, and proportions.',5,'learn');
INSERT INTO "categories" VALUES('inferential-statistics','Inferential & Hypothesis Testing','Z-scores, p-values, hypothesis tests, t-tests, and chi-square.',6,'learn');
INSERT INTO "categories" VALUES('calculators','Calculators','Standalone statistics calculators and tools.',7,'learn');
INSERT INTO "categories" VALUES('data-analysis','Data Analysis','Practical workflows for exploring, cleaning, and interpreting real datasets, from the first look at the data through to a conclusion you can defend.',7,'applied');
INSERT INTO "categories" VALUES('experiments-causality','Experiments & Causality','How to design A/B tests and experiments that answer the question you asked, and how to separate genuine cause from coincidence in observational data.',8,'applied');
INSERT INTO "categories" VALUES('time-series-forecasting','Forecasting & Time Series','Building and validating forecasts from time-ordered data: trend, seasonality, backtesting, and recognising when a model has quietly stopped working.',9,'applied');
INSERT INTO "categories" VALUES('machine-learning-statistics','Machine Learning Statistics','The statistical thinking behind machine learning: validation, overfitting, class imbalance, and reading model metrics without fooling yourself.',10,'applied');
CREATE TABLE keywords (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  article_slug TEXT NOT NULL REFERENCES articles(slug) ON DELETE CASCADE,
  keyword      TEXT NOT NULL,                  -- stored trimmed + lowercased
  is_primary   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(article_slug, keyword)
);
INSERT INTO "keywords" VALUES(1897,'how-to-find-the-mean','how to find the mean',1);
INSERT INTO "keywords" VALUES(1898,'how-to-find-the-mean','how to find average',0);
INSERT INTO "keywords" VALUES(1899,'how-to-find-the-mean','how to calculate average',0);
INSERT INTO "keywords" VALUES(1900,'how-to-find-the-mean','how to find the average of numbers',0);
INSERT INTO "keywords" VALUES(1901,'how-to-find-the-mean','how to find the mean in math',0);
INSERT INTO "keywords" VALUES(1902,'how-to-find-the-mean','how do i find average',0);
INSERT INTO "keywords" VALUES(1903,'how-to-find-the-mean','how do i find an average',0);
INSERT INTO "keywords" VALUES(1904,'how-to-find-the-mean','mean formula',0);
INSERT INTO "keywords" VALUES(1905,'how-to-find-the-mean','average formula',0);
INSERT INTO "keywords" VALUES(1906,'how-to-find-the-mean','formula for average',0);
INSERT INTO "keywords" VALUES(1907,'how-to-find-the-mean','formula for an average',0);
INSERT INTO "keywords" VALUES(1908,'how-to-find-the-mean','equation for average',0);
INSERT INTO "keywords" VALUES(1909,'what-is-an-average','what is the average',1);
INSERT INTO "keywords" VALUES(1910,'what-is-an-average','what is average',0);
INSERT INTO "keywords" VALUES(1911,'what-is-an-average','average definition',0);
INSERT INTO "keywords" VALUES(1912,'what-is-an-average','average meaning',0);
INSERT INTO "keywords" VALUES(1913,'what-is-an-average','average definitions',0);
INSERT INTO "keywords" VALUES(1914,'what-is-an-average','definition of average',0);
INSERT INTO "keywords" VALUES(1915,'what-is-an-average','define average',0);
INSERT INTO "keywords" VALUES(1916,'what-is-an-average','on average',0);
INSERT INTO "keywords" VALUES(1917,'what-is-an-average','grand average',0);
INSERT INTO "keywords" VALUES(1918,'what-is-an-average','sample mean',0);
INSERT INTO "keywords" VALUES(1919,'what-is-an-average','mean statistics',0);
INSERT INTO "keywords" VALUES(1920,'mean-vs-average','mean vs average',1);
INSERT INTO "keywords" VALUES(1921,'mean-vs-average','is mean average',0);
INSERT INTO "keywords" VALUES(1922,'mean-vs-average','is the mean the average',0);
INSERT INTO "keywords" VALUES(1923,'mean-vs-average','is mean same as average',0);
INSERT INTO "keywords" VALUES(1924,'mean-vs-average','is the mean the same as average',0);
INSERT INTO "keywords" VALUES(1925,'mean-vs-average','is mean the same as average',0);
INSERT INTO "keywords" VALUES(1926,'mean-vs-average','is average and mean the same',0);
INSERT INTO "keywords" VALUES(1927,'mean-vs-average','is average the same as mean',0);
INSERT INTO "keywords" VALUES(1928,'mean-vs-average','mean is the same as average',0);
INSERT INTO "keywords" VALUES(1929,'mean-vs-average','is the mean the same as the average',0);
INSERT INTO "keywords" VALUES(1930,'weighted-average','weighted average',1);
INSERT INTO "keywords" VALUES(1931,'weighted-average','weighted average calculator grades',0);
INSERT INTO "keywords" VALUES(1932,'weighted-average','average calculator for grades',0);
INSERT INTO "keywords" VALUES(1933,'weighted-average','how to calculate weighted average',0);
INSERT INTO "keywords" VALUES(1934,'weighted-average','weighted average formula',0);
INSERT INTO "keywords" VALUES(1935,'weighted-average','mean and weighted mean',0);
INSERT INTO "keywords" VALUES(1936,'how-to-find-the-median','how to find median',0);
INSERT INTO "keywords" VALUES(1937,'how-to-find-the-median','how to find the median',1);
INSERT INTO "keywords" VALUES(1938,'how-to-find-the-median','find the median',0);
INSERT INTO "keywords" VALUES(1939,'how-to-find-the-median','how to calculate median',0);
INSERT INTO "keywords" VALUES(1940,'how-to-find-the-median','median formula',0);
INSERT INTO "keywords" VALUES(1941,'how-to-find-the-median','formula for median',0);
INSERT INTO "keywords" VALUES(1942,'median-vs-average','median vs average',1);
INSERT INTO "keywords" VALUES(1943,'median-vs-average','is median an average',0);
INSERT INTO "keywords" VALUES(1944,'median-vs-average','is median the average',0);
INSERT INTO "keywords" VALUES(1945,'median-vs-average','is median average',0);
INSERT INTO "keywords" VALUES(1946,'median-vs-average','is the median the average',0);
INSERT INTO "keywords" VALUES(1947,'median-vs-average','what is median in math',0);
INSERT INTO "keywords" VALUES(1948,'median-vs-average','what does median mean in math',0);
INSERT INTO "keywords" VALUES(1949,'mean-median-mode-range','mean median mode range',1);
INSERT INTO "keywords" VALUES(1950,'mean-median-mode-range','how to find mean median and mode',0);
INSERT INTO "keywords" VALUES(1951,'mean-median-mode-range','how to calculate mean median and mode',0);
INSERT INTO "keywords" VALUES(1952,'mean-median-mode-range','how to find mode in math',0);
INSERT INTO "keywords" VALUES(1953,'mean-median-mode-range','what is mode in math',0);
INSERT INTO "keywords" VALUES(1954,'mean-median-mode-range','what does mode mean in math',0);
INSERT INTO "keywords" VALUES(1955,'standard-deviation','standard deviation',1);
INSERT INTO "keywords" VALUES(1956,'standard-deviation','standard deviation formula',0);
INSERT INTO "keywords" VALUES(1957,'standard-deviation','how to find standard deviation',0);
INSERT INTO "keywords" VALUES(1958,'standard-deviation','how to find the standard deviation',0);
INSERT INTO "keywords" VALUES(1959,'standard-deviation','standard deviation meaning',0);
INSERT INTO "keywords" VALUES(1960,'standard-deviation','what does standard deviation mean',0);
INSERT INTO "keywords" VALUES(1961,'standard-deviation','formula to standard deviation',0);
INSERT INTO "keywords" VALUES(1962,'standard-deviation','sample standard deviation',0);
INSERT INTO "keywords" VALUES(1963,'standard-deviation-symbol','standard deviation symbol',1);
INSERT INTO "keywords" VALUES(1964,'standard-deviation-symbol','symbol standard deviation',0);
INSERT INTO "keywords" VALUES(1965,'standard-deviation-symbol','symbols for standard deviation',0);
INSERT INTO "keywords" VALUES(1966,'standard-deviation-symbol','symbol of standard deviation',0);
INSERT INTO "keywords" VALUES(1967,'standard-deviation-symbol','symbol for standard deviation',0);
INSERT INTO "keywords" VALUES(1968,'standard-deviation-symbol','sign for standard deviation',0);
INSERT INTO "keywords" VALUES(1969,'standard-deviation-symbol','standard deviation sign',0);
INSERT INTO "keywords" VALUES(1970,'standard-deviation-symbol','standard deviation signs',0);
INSERT INTO "keywords" VALUES(1971,'standard-deviation-symbol','which of the following symbols identifies the population standard deviation',0);
INSERT INTO "keywords" VALUES(1972,'standard-deviation-excel','standard deviation excel',1);
INSERT INTO "keywords" VALUES(1973,'standard-deviation-excel','excel standard deviation',0);
INSERT INTO "keywords" VALUES(1974,'standard-deviation-excel','standard deviation by excel',0);
INSERT INTO "keywords" VALUES(1975,'standard-deviation-excel','standard deviation and excel',0);
INSERT INTO "keywords" VALUES(1976,'standard-deviation-excel','standard deviation with excel',0);
INSERT INTO "keywords" VALUES(1977,'standard-deviation-excel','standard deviation for excel',0);
INSERT INTO "keywords" VALUES(1978,'standard-deviation-excel','excel function standard deviation',0);
INSERT INTO "keywords" VALUES(1979,'variance','variance',1);
INSERT INTO "keywords" VALUES(1980,'variance','variance definition',0);
INSERT INTO "keywords" VALUES(1981,'variance','formula for variance',0);
INSERT INTO "keywords" VALUES(1982,'variance','variance equation',0);
INSERT INTO "keywords" VALUES(1983,'variance','how to calculate variance',0);
INSERT INTO "keywords" VALUES(1984,'variance','how to find variance',0);
INSERT INTO "keywords" VALUES(1985,'variance','standard deviation vs variance',0);
INSERT INTO "keywords" VALUES(1986,'variance','variance vs standard deviation',0);
INSERT INTO "keywords" VALUES(1987,'variance','standard deviation versus variance',0);
INSERT INTO "keywords" VALUES(1988,'sample-variance-formula','variance for sample formula',0);
INSERT INTO "keywords" VALUES(1989,'sample-variance-formula','formula for variance of a sample',0);
INSERT INTO "keywords" VALUES(1990,'sample-variance-formula','variance formula sample',0);
INSERT INTO "keywords" VALUES(1991,'sample-variance-formula','variance formula for sample',0);
INSERT INTO "keywords" VALUES(1992,'sample-variance-formula','sample variance formulas',0);
INSERT INTO "keywords" VALUES(1993,'sample-variance-formula','sample variance formula',1);
INSERT INTO "keywords" VALUES(1994,'sample-variance-formula','sample variance equation',0);
INSERT INTO "keywords" VALUES(1995,'sample-variance-formula','variance formula example',0);
INSERT INTO "keywords" VALUES(1996,'sample-variance-formula','sampling variance formula',0);
INSERT INTO "keywords" VALUES(1997,'mean-absolute-deviation','mean absolute deviation',1);
INSERT INTO "keywords" VALUES(1998,'mean-absolute-deviation','what is mean absolute deviation',0);
INSERT INTO "keywords" VALUES(1999,'mean-absolute-deviation','using mean and mean absolute deviation to compare data iready',0);
INSERT INTO "keywords" VALUES(2000,'mean-absolute-deviation','deviation mean',0);
INSERT INTO "keywords" VALUES(2001,'mean-absolute-deviation','coefficient of variation',0);
INSERT INTO "keywords" VALUES(2002,'how-to-find-the-range','how to find the range',1);
INSERT INTO "keywords" VALUES(2003,'how-to-find-the-range','how to find range',0);
INSERT INTO "keywords" VALUES(2004,'how-to-find-the-range','how do you find the range',0);
INSERT INTO "keywords" VALUES(2005,'how-to-find-the-range','how to calculate range',0);
INSERT INTO "keywords" VALUES(2006,'how-to-find-the-range','how to calculate a range',0);
INSERT INTO "keywords" VALUES(2007,'how-to-find-the-range','how to calculate the range',0);
INSERT INTO "keywords" VALUES(2008,'how-to-find-the-range','how to calculate for range',0);
INSERT INTO "keywords" VALUES(2009,'how-to-find-the-range','how do you calculate range',0);
INSERT INTO "keywords" VALUES(2010,'how-to-find-the-range','how do you calculate the range',0);
INSERT INTO "keywords" VALUES(2011,'how-to-find-the-range','how do i calculate range',0);
INSERT INTO "keywords" VALUES(2012,'how-to-find-the-range','how do you find range in a data set',0);
INSERT INTO "keywords" VALUES(2013,'how-to-find-the-range','how to find the range of a data set',0);
INSERT INTO "keywords" VALUES(2014,'how-to-find-the-range','range in statistics',0);
INSERT INTO "keywords" VALUES(2015,'how-to-find-the-range','what is range in statistics',0);
INSERT INTO "keywords" VALUES(2016,'how-to-find-the-range','range formula',0);
INSERT INTO "keywords" VALUES(2017,'how-to-find-the-range','range of data',0);
INSERT INTO "keywords" VALUES(2018,'how-to-find-the-range','range in statistics formula',0);
INSERT INTO "keywords" VALUES(2019,'how-to-find-outliers','how to find outliers',1);
INSERT INTO "keywords" VALUES(2020,'how-to-find-outliers','how to find an outlier in statistics',0);
INSERT INTO "keywords" VALUES(2021,'how-to-find-outliers','how to calculate outlier',0);
INSERT INTO "keywords" VALUES(2022,'how-to-find-outliers','outliers formula',0);
INSERT INTO "keywords" VALUES(2023,'how-to-find-outliers','formula for outlier',0);
INSERT INTO "keywords" VALUES(2024,'how-to-find-outliers','outlier formula',0);
INSERT INTO "keywords" VALUES(2025,'interquartile-range','interquartile range',1);
INSERT INTO "keywords" VALUES(2026,'interquartile-range','what is interquartile range',0);
INSERT INTO "keywords" VALUES(2027,'interquartile-range','what is the interquartile range',0);
INSERT INTO "keywords" VALUES(2028,'interquartile-range','how to find the interquartile range',0);
INSERT INTO "keywords" VALUES(2029,'interquartile-range','how to find interquartile range',0);
INSERT INTO "keywords" VALUES(2030,'interquartile-range','iqr formula',0);
INSERT INTO "keywords" VALUES(2031,'percentiles','percentile meaning',1);
INSERT INTO "keywords" VALUES(2032,'percentiles','meaning of percentile',0);
INSERT INTO "keywords" VALUES(2033,'percentiles','percentile definition',0);
INSERT INTO "keywords" VALUES(2034,'percentiles','definition of percentile',0);
INSERT INTO "keywords" VALUES(2035,'percentiles','define percentile',0);
INSERT INTO "keywords" VALUES(2036,'percentiles','how to calculate percentile',0);
INSERT INTO "keywords" VALUES(2037,'percentiles','how to calculate percentiles',0);
INSERT INTO "keywords" VALUES(2038,'frequency-table','frequency table',1);
INSERT INTO "keywords" VALUES(2039,'frequency-table','relative frequency table',0);
INSERT INTO "keywords" VALUES(2040,'frequency-table','how to find relative frequency',0);
INSERT INTO "keywords" VALUES(2041,'frequency-table','what is the relative frequency in statistics',0);
INSERT INTO "keywords" VALUES(2042,'frequency-table','frequency distribution',0);
INSERT INTO "keywords" VALUES(2043,'frequency-table','statistics frequency polygon',0);
INSERT INTO "keywords" VALUES(2044,'how-to-find-frequency-statistics','frequency in statistics',1);
INSERT INTO "keywords" VALUES(2045,'how-to-find-frequency-statistics','what is frequency in statistics',0);
INSERT INTO "keywords" VALUES(2046,'how-to-find-frequency-statistics','frequency statistics',0);
INSERT INTO "keywords" VALUES(2047,'how-to-find-frequency-statistics','frequency distribution statistics',0);
INSERT INTO "keywords" VALUES(2048,'how-to-find-frequency-statistics','grouped frequency distribution',0);
INSERT INTO "keywords" VALUES(2049,'how-to-find-frequency-statistics','class frequency',0);
INSERT INTO "keywords" VALUES(2050,'probability-formula','probability formula',1);
INSERT INTO "keywords" VALUES(2051,'probability-formula','how to calculate probability',0);
INSERT INTO "keywords" VALUES(2052,'probability-formula','how to find probability',0);
INSERT INTO "keywords" VALUES(2053,'probability-formula','probability and statistics',0);
INSERT INTO "keywords" VALUES(2054,'probability-formula','conditional probability formula',0);
INSERT INTO "keywords" VALUES(2055,'probability-formula','expectation probability formula',0);
INSERT INTO "keywords" VALUES(2056,'probability-formula','formula for expected value',0);
INSERT INTO "keywords" VALUES(2057,'probability-formula','binomial probability formula',0);
INSERT INTO "keywords" VALUES(2058,'probability-distribution','probability distribution',1);
INSERT INTO "keywords" VALUES(2059,'probability-distribution','distribution mean',0);
INSERT INTO "keywords" VALUES(2060,'probability-distribution','marginal probability distribution',0);
INSERT INTO "keywords" VALUES(2061,'probability-distribution','marginal distribution definition',0);
INSERT INTO "keywords" VALUES(2062,'probability-distribution','marginal distribution meaning',0);
INSERT INTO "keywords" VALUES(2063,'probability-distribution','distribution of population',0);
INSERT INTO "keywords" VALUES(2064,'probability-distribution','distribution population',0);
INSERT INTO "keywords" VALUES(2065,'probability-distribution','distribution of the population',0);
INSERT INTO "keywords" VALUES(2066,'probability-distribution','bayesian statistics',0);
INSERT INTO "keywords" VALUES(2067,'normal-distribution','normal distribution',1);
INSERT INTO "keywords" VALUES(2068,'normal-distribution','gaussian distribution',0);
INSERT INTO "keywords" VALUES(2069,'normal-distribution','normal distribution chart',0);
INSERT INTO "keywords" VALUES(2070,'normal-distribution','normal distribution curves',0);
INSERT INTO "keywords" VALUES(2071,'normal-distribution','bell curve normal distribution',0);
INSERT INTO "keywords" VALUES(2072,'normal-distribution','normal distribution bell curve',0);
INSERT INTO "keywords" VALUES(2073,'normal-distribution','standard gaussian distribution',0);
INSERT INTO "keywords" VALUES(2074,'z-table','z normal distribution table',0);
INSERT INTO "keywords" VALUES(2075,'z-table','standard normal z-table',0);
INSERT INTO "keywords" VALUES(2076,'z-table','z score table',1);
INSERT INTO "keywords" VALUES(2077,'z-table','z-score table',0);
INSERT INTO "keywords" VALUES(2078,'z-table','table of z-score',0);
INSERT INTO "keywords" VALUES(2079,'z-table','z table normal',0);
INSERT INTO "keywords" VALUES(2080,'z-table','normal dist z table',0);
INSERT INTO "keywords" VALUES(2081,'z-table','distribution z table',0);
INSERT INTO "keywords" VALUES(2082,'z-table','normal distribution table',0);
INSERT INTO "keywords" VALUES(2083,'z-table','normal distribution tables',0);
INSERT INTO "keywords" VALUES(2084,'z-table','table of normal distribution',0);
INSERT INTO "keywords" VALUES(2085,'binomial-distribution','binomial distribution',1);
INSERT INTO "keywords" VALUES(2086,'binomial-distribution','binomial distribution formula',0);
INSERT INTO "keywords" VALUES(2087,'binomial-distribution','binomial distribution formulas',0);
INSERT INTO "keywords" VALUES(2088,'binomial-distribution','bernoulli''s distribution',0);
INSERT INTO "keywords" VALUES(2089,'binomial-distribution','geometric distribution',0);
INSERT INTO "keywords" VALUES(2090,'skewed-distribution','distribution skewed left',0);
INSERT INTO "keywords" VALUES(2091,'skewed-distribution','left skewed distribution',1);
INSERT INTO "keywords" VALUES(2092,'skewed-distribution','skewed left distribution',0);
INSERT INTO "keywords" VALUES(2093,'skewed-distribution','left-skewed distribution',0);
INSERT INTO "keywords" VALUES(2094,'skewed-distribution','left vs right-skewed distribution',0);
INSERT INTO "keywords" VALUES(2095,'skewed-distribution','bimodality distribution',0);
INSERT INTO "keywords" VALUES(2096,'exponential-distribution','exponential distribution',1);
INSERT INTO "keywords" VALUES(2097,'exponential-distribution','exponential probability distribution',0);
INSERT INTO "keywords" VALUES(2098,'exponential-distribution','probability distribution exponential',0);
INSERT INTO "keywords" VALUES(2099,'exponential-distribution','uniform distribution',0);
INSERT INTO "keywords" VALUES(2100,'exponential-distribution','gamma distribution',0);
INSERT INTO "keywords" VALUES(2101,'exponential-distribution','lognormal distribution',0);
INSERT INTO "keywords" VALUES(2102,'correlation-coefficient','correlation coefficient',1);
INSERT INTO "keywords" VALUES(2103,'correlation-coefficient','correlation coefficients',0);
INSERT INTO "keywords" VALUES(2104,'correlation-coefficient','what is a correlation coefficient',0);
INSERT INTO "keywords" VALUES(2105,'correlation-coefficient','correlation coefficient formula',0);
INSERT INTO "keywords" VALUES(2106,'correlation-coefficient','coefficient of correlation formula',0);
INSERT INTO "keywords" VALUES(2107,'correlation-coefficient','coefficient and correlation formula',0);
INSERT INTO "keywords" VALUES(2108,'correlation-coefficient','how to find correlation coefficient',0);
INSERT INTO "keywords" VALUES(2109,'correlation-coefficient','which value of r indicates a stronger correlation',0);
INSERT INTO "keywords" VALUES(2110,'correlation-coefficient','which of the following r values represents the strongest correlation',0);
INSERT INTO "keywords" VALUES(2111,'correlation-coefficient','which of the following r-values represents the strongest correlation',0);
INSERT INTO "keywords" VALUES(2112,'correlation-coefficient','which of these r-values represents the weakest correlation',0);
INSERT INTO "keywords" VALUES(2113,'correlation-coefficient','which of these r values represents the weakest correlation',0);
INSERT INTO "keywords" VALUES(2114,'pearson-correlation-coefficient','pearson correlation',1);
INSERT INTO "keywords" VALUES(2115,'pearson-correlation-coefficient','pearson''s correlation',0);
INSERT INTO "keywords" VALUES(2116,'pearson-correlation-coefficient','pearson''s correlation coefficient',0);
INSERT INTO "keywords" VALUES(2117,'pearson-correlation-coefficient','pearson coefficient correlation',0);
INSERT INTO "keywords" VALUES(2118,'pearson-correlation-coefficient','pearson product moment correlation',0);
INSERT INTO "keywords" VALUES(2119,'pearson-correlation-coefficient','pearson rank correlation',0);
INSERT INTO "keywords" VALUES(2120,'pearson-correlation-coefficient','spearman rank correlation coefficient',0);
INSERT INTO "keywords" VALUES(2121,'pearson-correlation-coefficient','covariance formula',0);
INSERT INTO "keywords" VALUES(2122,'what-is-correlation','correlation definition',1);
INSERT INTO "keywords" VALUES(2123,'what-is-correlation','correlation def',0);
INSERT INTO "keywords" VALUES(2124,'what-is-correlation','correlation meaning',0);
INSERT INTO "keywords" VALUES(2125,'what-is-correlation','correlation basics',0);
INSERT INTO "keywords" VALUES(2126,'what-is-correlation','positive correlation',0);
INSERT INTO "keywords" VALUES(2127,'what-is-correlation','mean correlation',0);
INSERT INTO "keywords" VALUES(2128,'what-is-correlation','which table shows a positive correlation',0);
INSERT INTO "keywords" VALUES(2129,'correlation-vs-causation','correlation vs causation',1);
INSERT INTO "keywords" VALUES(2130,'correlation-vs-causation','which correlation is most likely a causation',0);
INSERT INTO "keywords" VALUES(2131,'correlation-vs-causation','correlation does not imply causation',0);
INSERT INTO "keywords" VALUES(2132,'correlation-vs-causation','true or false correlation implies causation',0);
INSERT INTO "keywords" VALUES(2133,'correlation-vs-causation','true or false: correlation implies causation',0);
INSERT INTO "keywords" VALUES(2134,'correlation-vs-causation','spurious correlation',0);
INSERT INTO "keywords" VALUES(2135,'correlation-vs-causation','correlation vs identity example',0);
INSERT INTO "keywords" VALUES(2136,'linear-regression','linear regression',1);
INSERT INTO "keywords" VALUES(2137,'linear-regression','what is linear regression',0);
INSERT INTO "keywords" VALUES(2138,'linear-regression','linear regression formula',0);
INSERT INTO "keywords" VALUES(2139,'linear-regression','regression analysis',0);
INSERT INTO "keywords" VALUES(2140,'linear-regression','regression equation',0);
INSERT INTO "keywords" VALUES(2141,'linear-regression','regression equations',0);
INSERT INTO "keywords" VALUES(2142,'linear-regression','which regression equation best fits these data',0);
INSERT INTO "keywords" VALUES(2143,'linear-regression','which regression equation best fits the data',0);
INSERT INTO "keywords" VALUES(2144,'linear-regression','logistic regression',0);
INSERT INTO "keywords" VALUES(2145,'regression-to-the-mean','regression to the mean',1);
INSERT INTO "keywords" VALUES(2146,'regression-to-the-mean','mean regression',0);
INSERT INTO "keywords" VALUES(2147,'regression-to-the-mean','regression of the mean',0);
INSERT INTO "keywords" VALUES(2148,'regression-to-the-mean','regression to the mean definition',0);
INSERT INTO "keywords" VALUES(2149,'z-score','z score',1);
INSERT INTO "keywords" VALUES(2150,'z-score','z score formula',0);
INSERT INTO "keywords" VALUES(2151,'z-score','how to find z score',0);
INSERT INTO "keywords" VALUES(2152,'z-score','how to calculate z score',0);
INSERT INTO "keywords" VALUES(2153,'z-score','z-score chart',0);
INSERT INTO "keywords" VALUES(2154,'z-score','standard normal distribution',0);
INSERT INTO "keywords" VALUES(2155,'p-value','p value',1);
INSERT INTO "keywords" VALUES(2156,'p-value','what is p value',0);
INSERT INTO "keywords" VALUES(2157,'p-value','what is p value in statistics',0);
INSERT INTO "keywords" VALUES(2158,'p-value','how to find p value',0);
INSERT INTO "keywords" VALUES(2159,'p-value','how to calculate p value',0);
INSERT INTO "keywords" VALUES(2160,'p-value','p-value formula',0);
INSERT INTO "keywords" VALUES(2161,'null-hypothesis','what is a null hypothesis',1);
INSERT INTO "keywords" VALUES(2162,'null-hypothesis','null hypothesis meaning',0);
INSERT INTO "keywords" VALUES(2163,'null-hypothesis','null hypothesis example',0);
INSERT INTO "keywords" VALUES(2164,'null-hypothesis','example of a null hypothesis',0);
INSERT INTO "keywords" VALUES(2165,'null-hypothesis','examples of hypothesis',0);
INSERT INTO "keywords" VALUES(2166,'null-hypothesis','what does null mean',0);
INSERT INTO "keywords" VALUES(2167,'null-hypothesis','what does null null mean',0);
INSERT INTO "keywords" VALUES(2168,'null-hypothesis','what does in null mean',0);
INSERT INTO "keywords" VALUES(2169,'null-hypothesis','null what does it mean',0);
INSERT INTO "keywords" VALUES(2170,'test-statistic','test statistic',1);
INSERT INTO "keywords" VALUES(2171,'test-statistic','formula for test statistic',0);
INSERT INTO "keywords" VALUES(2172,'test-statistic','test statistic formula',0);
INSERT INTO "keywords" VALUES(2173,'test-statistic','how to find critical value',0);
INSERT INTO "keywords" VALUES(2174,'test-statistic','how to find degrees of freedom',0);
INSERT INTO "keywords" VALUES(2175,'test-statistic','t distribution table',0);
INSERT INTO "keywords" VALUES(2176,'test-statistic','t table distribution',0);
INSERT INTO "keywords" VALUES(2177,'test-statistic','table for t distribution',0);
INSERT INTO "keywords" VALUES(2178,'test-statistic','what is df in statistics',0);
INSERT INTO "keywords" VALUES(2179,'test-statistic','what is a degree of freedom in statistics',0);
INSERT INTO "keywords" VALUES(2180,'test-statistic','what is d f in statistics',0);
INSERT INTO "keywords" VALUES(2181,'t-test','paired t-test',1);
INSERT INTO "keywords" VALUES(2182,'t-test','paired difference t-test',0);
INSERT INTO "keywords" VALUES(2183,'t-test','t test equation',0);
INSERT INTO "keywords" VALUES(2184,'t-test','t-test equation',0);
INSERT INTO "keywords" VALUES(2185,'t-test','student t-test formula',0);
INSERT INTO "keywords" VALUES(2186,'t-test','two sample t-test',0);
INSERT INTO "keywords" VALUES(2187,'t-test','2 sample t-test',0);
INSERT INTO "keywords" VALUES(2188,'t-test','t test for 2 samples',0);
INSERT INTO "keywords" VALUES(2189,'t-test','t test for two sample',0);
INSERT INTO "keywords" VALUES(2190,'t-test','t test with two samples',0);
INSERT INTO "keywords" VALUES(2191,'chi-square-test','chi square test',1);
INSERT INTO "keywords" VALUES(2192,'chi-square-test','chi square tests',0);
INSERT INTO "keywords" VALUES(2193,'chi-square-test','chi-square formula',0);
INSERT INTO "keywords" VALUES(2194,'chi-square-test','chi squared formula',0);
INSERT INTO "keywords" VALUES(2195,'chi-square-test','chi-squared formula',0);
INSERT INTO "keywords" VALUES(2196,'chi-square-test','formula for chi square test',0);
INSERT INTO "keywords" VALUES(2197,'chi-square-test','formula for chi square',0);
INSERT INTO "keywords" VALUES(2198,'chi-square-test','formula for chi squared',0);
INSERT INTO "keywords" VALUES(2199,'chi-square-test','chi square equation',0);
INSERT INTO "keywords" VALUES(2200,'chi-square-test','chi-square equation',0);
INSERT INTO "keywords" VALUES(2201,'chi-square-test','chi squared equation',0);
INSERT INTO "keywords" VALUES(2202,'chi-square-test','chi-square test equation',0);
INSERT INTO "keywords" VALUES(2203,'chi-square-distribution','chi square distribution',1);
INSERT INTO "keywords" VALUES(2204,'chi-square-distribution','chi-square distribution',0);
INSERT INTO "keywords" VALUES(2205,'chi-square-distribution','chi-squared distribution',0);
INSERT INTO "keywords" VALUES(2206,'chi-square-distribution','chi-square probability distribution',0);
INSERT INTO "keywords" VALUES(2207,'chi-square-distribution','chi-square test distribution',0);
INSERT INTO "keywords" VALUES(2208,'chi-square-distribution','chi-square function',0);
INSERT INTO "keywords" VALUES(2209,'chi-square-distribution','chi squared probability density function',0);
INSERT INTO "keywords" VALUES(2210,'chi-square-distribution','chi square value table',0);
INSERT INTO "keywords" VALUES(2211,'chi-square-distribution','table for chi square test',0);
INSERT INTO "keywords" VALUES(2212,'confidence-interval','confidence interval formula',1);
INSERT INTO "keywords" VALUES(2213,'confidence-interval','95 confidence interval',0);
INSERT INTO "keywords" VALUES(2214,'confidence-interval','what is a confidence interval',0);
INSERT INTO "keywords" VALUES(2215,'fundamental-statistics','fundamental statistics',1);
INSERT INTO "keywords" VALUES(2216,'fundamental-statistics','what is statistics',0);
INSERT INTO "keywords" VALUES(2217,'fundamental-statistics','statistics definition',0);
INSERT INTO "keywords" VALUES(2218,'fundamental-statistics','statistics math',0);
INSERT INTO "keywords" VALUES(2219,'fundamental-statistics','what do statistics mean',0);
INSERT INTO "keywords" VALUES(2220,'fundamental-statistics','what does statistics mean',0);
INSERT INTO "keywords" VALUES(2221,'fundamental-statistics','what does statistics means',0);
INSERT INTO "keywords" VALUES(2222,'fundamental-statistics','which situation involves descriptive statistics',0);
INSERT INTO "keywords" VALUES(2223,'parameter-vs-statistic','parameter vs statistics',1);
INSERT INTO "keywords" VALUES(2224,'parameter-vs-statistic','parameters vs statistics',0);
INSERT INTO "keywords" VALUES(2225,'parameter-vs-statistic','statistics vs parameters',0);
INSERT INTO "keywords" VALUES(2226,'parameter-vs-statistic','statistics vs parameter',0);
INSERT INTO "keywords" VALUES(2227,'parameter-vs-statistic','statistics or parameter',0);
INSERT INTO "keywords" VALUES(2228,'parameter-vs-statistic','statistics or parameters',0);
INSERT INTO "keywords" VALUES(2229,'parameter-vs-statistic','parameters or statistics',0);
INSERT INTO "keywords" VALUES(2230,'parameter-vs-statistic','statistics versus parameters',0);
INSERT INTO "keywords" VALUES(2231,'parameter-vs-statistic','parameter definition statistics',0);
INSERT INTO "keywords" VALUES(2232,'statistics-symbols-cheatsheet','statistics symbols',0);
INSERT INTO "keywords" VALUES(2233,'statistics-symbols-cheatsheet','statistics and or symbols',0);
INSERT INTO "keywords" VALUES(2234,'statistics-symbols-cheatsheet','what is mu 0 in statistics',0);
INSERT INTO "keywords" VALUES(2235,'statistics-symbols-cheatsheet','statistics symbols cheat sheet',1);
INSERT INTO "keywords" VALUES(2236,'proportions-in-statistics','proportion in statistics',1);
INSERT INTO "keywords" VALUES(2237,'proportions-in-statistics','sample proportion',0);
INSERT INTO "keywords" VALUES(2238,'proportions-in-statistics','population proportion',0);
INSERT INTO "keywords" VALUES(2239,'proportions-in-statistics','confidence interval for a proportion',0);
INSERT INTO "keywords" VALUES(2240,'proportions-in-statistics','proportion statistics',0);
INSERT INTO "keywords" VALUES(2241,'proportions-in-statistics','sample proportion formula',0);
INSERT INTO "keywords" VALUES(2242,'proportions-in-statistics','hypothesis test for a proportion',0);
INSERT INTO "keywords" VALUES(2243,'proportions-in-statistics','population proportion formula',0);
INSERT INTO "keywords" VALUES(2244,'proportions-in-statistics','proportion formula statistics',0);
INSERT INTO "keywords" VALUES(2245,'proportions-in-statistics','pooled proportion',0);
INSERT INTO "keywords" VALUES(2246,'proportions-in-statistics','proportion definition in statistics',0);
INSERT INTO "keywords" VALUES(2247,'proportions-in-statistics','sampling distribution of the sample proportion',0);
INSERT INTO "keywords" VALUES(2248,'proportions-in-statistics','point estimate of proportion',0);
INSERT INTO "keywords" VALUES(2249,'validity-in-statistics','construct validity statistics',1);
INSERT INTO "keywords" VALUES(2250,'validity-in-statistics','external validity statistics',0);
INSERT INTO "keywords" VALUES(2251,'types-of-variables','qualitative vs quantitative',1);
INSERT INTO "keywords" VALUES(2252,'types-of-variables','quantitative vs qualitative',0);
INSERT INTO "keywords" VALUES(2253,'types-of-variables','qualitative vs quantitative research',0);
INSERT INTO "keywords" VALUES(2254,'types-of-variables','discrete vs continuous variables',0);
INSERT INTO "keywords" VALUES(2255,'binomial-theorem','binomial theorem',1);
INSERT INTO "keywords" VALUES(2256,'binomial-theorem','pascal''s triangle',0);
INSERT INTO "keywords" VALUES(2257,'central-limit-theorem','central limit theorem',1);
INSERT INTO "keywords" VALUES(2258,'permutations','permutation',1);
INSERT INTO "keywords" VALUES(2259,'permutations','permutation formula',0);
INSERT INTO "keywords" VALUES(2260,'combinations','combination formula',1);
INSERT INTO "keywords" VALUES(2261,'type-i-and-type-ii-errors','type i and type ii errors',1);
INSERT INTO "keywords" VALUES(2262,'type-i-and-type-ii-errors','type 1 and type 2 errors',0);
INSERT INTO "keywords" VALUES(2263,'type-i-and-type-ii-errors','type i vs type ii errors',0);
INSERT INTO "keywords" VALUES(2264,'type-i-and-type-ii-errors','types of statistical errors',0);
INSERT INTO "keywords" VALUES(2265,'bayes-theorem','bayes rule',1);
INSERT INTO "keywords" VALUES(2266,'bayes-theorem','bayesian',0);
INSERT INTO "keywords" VALUES(2267,'levels-of-measurement','ordinal variable vs nominal',1);
INSERT INTO "keywords" VALUES(2268,'levels-of-measurement','nominal ordinal interval or ratio',0);
INSERT INTO "keywords" VALUES(2269,'mann-whitney-u-test','mann-whitney t-test',1);
INSERT INTO "keywords" VALUES(2270,'mann-whitney-u-test','mann-whitney u test wilcoxon rank sum',0);
INSERT INTO "keywords" VALUES(2271,'mann-whitney-u-test','wilcoxon rank sum test',0);
INSERT INTO "keywords" VALUES(2272,'mann-whitney-u-test','wilcoxon sum rank test',0);
INSERT INTO "keywords" VALUES(2273,'r-squared-adjusted-r-squared','coefficient of determination',1);
INSERT INTO "keywords" VALUES(2274,'reliability-cronbachs-alpha-cohens-kappa','cronbach''s alpha',1);
INSERT INTO "keywords" VALUES(2275,'reliability-cronbachs-alpha-cohens-kappa','cronbach alpha',0);
INSERT INTO "keywords" VALUES(2276,'reliability-cronbachs-alpha-cohens-kappa','cohen''s kappa',0);
INSERT INTO "keywords" VALUES(2277,'reliability-cronbachs-alpha-cohens-kappa','cohen kappa',0);
INSERT INTO "keywords" VALUES(2278,'effect-size','effect size',1);
INSERT INTO "keywords" VALUES(2279,'effect-size','effect sizes',0);
INSERT INTO "keywords" VALUES(2280,'effect-size','effect size d',0);
INSERT INTO "keywords" VALUES(2281,'kruskal-wallis-test','kruskal-wallis analysis of variance',1);
INSERT INTO "keywords" VALUES(2282,'kruskal-wallis-test','kruskal wallis analysis of variance',0);
INSERT INTO "keywords" VALUES(2283,'kruskal-wallis-test','kruskal wallis one way analysis of variance',0);
INSERT INTO "keywords" VALUES(2284,'paired-vs-independent-t-test','t-test and paired t-test',1);
INSERT INTO "keywords" VALUES(2285,'paired-vs-independent-t-test','t test and paired t test',0);
INSERT INTO "keywords" VALUES(2286,'paired-vs-independent-t-test','example of independent t-test',0);
INSERT INTO "keywords" VALUES(2287,'paired-vs-independent-t-test','example of paired t-test',0);
INSERT INTO "keywords" VALUES(2288,'empirical-rule','empirical rule statistics',1);
CREATE TABLE reviews (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  article_slug TEXT NOT NULL REFERENCES articles(slug) ON DELETE CASCADE,
  score        INTEGER,
  passed       INTEGER NOT NULL DEFAULT 0,     -- 1 = PASS, 0 = CHANGES_REQUESTED
  notes        TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO "reviews" VALUES(1,'standard-deviation-symbol',96,1,'All 9 KWs present, 2877 words, NIST link resolves 200, no H1 in body, no hand-typed hrefs, no cannibalization, draft:true; minor: primary KW count 11x is on the high side but reads naturally','2026-06-14 17:20:27');
INSERT INTO "reviews" VALUES(2,'how-to-find-the-range',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-15 18:56:08');
INSERT INTO "reviews" VALUES(3,'correlation-vs-causation',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-17 21:52:49');
INSERT INTO "reviews" VALUES(4,'what-is-an-average',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-18 01:09:48');
INSERT INTO "reviews" VALUES(5,'linear-regression',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-18 21:55:12');
INSERT INTO "reviews" VALUES(6,'mean-absolute-deviation',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-19 01:11:34');
INSERT INTO "reviews" VALUES(7,'parameter-vs-statistic',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate); sandbox-network blocked all outbound curl (403 for all hosts incl example.com) -- treated as sandbox-egress warning per routine spec','2026-06-19 21:55:42');
INSERT INTO "reviews" VALUES(8,'weighted-average',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-20 21:57:01');
INSERT INTO "reviews" VALUES(9,'skewed-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-21 01:09:10');
INSERT INTO "reviews" VALUES(10,'what-is-correlation',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-21 21:57:21');
INSERT INTO "reviews" VALUES(11,'probability-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-22 02:27:07');
INSERT INTO "reviews" VALUES(12,'frequency-table',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-22 21:55:26');
INSERT INTO "reviews" VALUES(13,'standard-deviation-excel',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-23 01:10:52');
INSERT INTO "reviews" VALUES(14,'fundamental-statistics',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-23 19:38:07');
INSERT INTO "reviews" VALUES(15,'mean-vs-average',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-23 21:54:33');
INSERT INTO "reviews" VALUES(16,'z-table',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-24 01:11:33');
INSERT INTO "reviews" VALUES(17,'median-vs-average',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-24 21:53:01');
INSERT INTO "reviews" VALUES(18,'z-score',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-25 01:10:16');
INSERT INTO "reviews" VALUES(19,'test-statistic',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-25 21:54:29');
INSERT INTO "reviews" VALUES(20,'probability-formula',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-26 01:07:08');
INSERT INTO "reviews" VALUES(21,'how-to-find-outliers',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-28 21:52:53');
INSERT INTO "reviews" VALUES(22,'percentiles',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-29 01:11:53');
INSERT INTO "reviews" VALUES(23,'interquartile-range',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-29 21:54:14');
INSERT INTO "reviews" VALUES(24,'how-to-find-the-mean',90,1,'automated routine self-review + green build gate (astro check 0/0/0 + vitest 89/89 + build 60 pages / 0 link violations)','2026-06-30 01:10:32');
INSERT INTO "reviews" VALUES(25,'variance',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-06-30 21:54:29');
INSERT INTO "reviews" VALUES(26,'correlation-coefficient',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-01 01:11:06');
INSERT INTO "reviews" VALUES(27,'mean-median-mode-range',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-01 21:52:15');
INSERT INTO "reviews" VALUES(28,'t-test',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-02 01:19:09');
INSERT INTO "reviews" VALUES(29,'binomial-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-02 21:53:08');
INSERT INTO "reviews" VALUES(30,'exponential-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-03 01:14:16');
INSERT INTO "reviews" VALUES(31,'pearson-correlation-coefficient',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-03 21:51:37');
INSERT INTO "reviews" VALUES(32,'sample-variance-formula',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-04 01:15:39');
INSERT INTO "reviews" VALUES(33,'p-value',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-04 21:50:44');
INSERT INTO "reviews" VALUES(34,'chi-square-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-05 01:17:16');
INSERT INTO "reviews" VALUES(35,'normal-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-05 21:52:02');
INSERT INTO "reviews" VALUES(36,'standard-deviation',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-06 01:14:57');
INSERT INTO "reviews" VALUES(37,'how-to-find-the-median',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-07 01:18:02');
INSERT INTO "reviews" VALUES(38,'chi-square-test',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-07 21:54:51');
INSERT INTO "reviews" VALUES(39,'null-hypothesis',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-08 01:17:55');
INSERT INTO "reviews" VALUES(40,'statistics-symbols-cheatsheet',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-11 15:51:22');
INSERT INTO "reviews" VALUES(41,'proportions-in-statistics',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-12 01:18:31');
INSERT INTO "reviews" VALUES(42,'how-to-find-frequency-statistics',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-13 01:18:54');
INSERT INTO "reviews" VALUES(43,'regression-to-the-mean',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-14 01:20:07');
INSERT INTO "reviews" VALUES(44,'confidence-interval',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-15 01:14:41');
INSERT INTO "reviews" VALUES(45,'types-of-variables',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-16 01:22:04');
INSERT INTO "reviews" VALUES(46,'binomial-theorem',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-17 01:17:02');
INSERT INTO "reviews" VALUES(47,'central-limit-theorem',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-18 01:18:45');
INSERT INTO "reviews" VALUES(48,'permutations',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-19 01:21:37');
INSERT INTO "reviews" VALUES(49,'combinations',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-20 01:19:46');
INSERT INTO "reviews" VALUES(50,'type-i-and-type-ii-errors',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-21 01:18:53');
INSERT INTO "reviews" VALUES(51,'bayes-theorem',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-22 01:17:30');
INSERT INTO "reviews" VALUES(52,'levels-of-measurement',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-23 01:22:16');
INSERT INTO "reviews" VALUES(53,'mann-whitney-u-test',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-24 01:24:20');
INSERT INTO "reviews" VALUES(54,'r-squared-adjusted-r-squared',50,0,'deferred by cloud routine: slug ''r-squared-adjusted-r-squared'' contains none of the significant tokens of primaryKeyword ''coefficient of determination'' (tokens: coefficient, determination). QA hard-fail on slug/keyword mismatch. DB notes acknowledge this conflict: ''SEO emphasis should prioritize coefficient of determination, title keeps R-Squared for readability''. Article content is complete: 2911 words, all other QA hard-checks pass (H2 headings, no H1, no LaTeX, draft:true, RelatedLinks, authoritative external links, internal links via routes). Build gate passes (89 pages, 0 link/meta-description violations). Human decision needed: either rename slug to coefficient-of-determination (URL change) or update primaryKeyword in DB to match the slug tokens.','2026-07-25 01:22:55');
INSERT INTO "reviews" VALUES(55,'reliability-cronbachs-alpha-cohens-kappa',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-26 01:19:29');
INSERT INTO "reviews" VALUES(56,'effect-size',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-27 01:19:02');
INSERT INTO "reviews" VALUES(57,'kruskal-wallis-test',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-28 01:18:03');
INSERT INTO "reviews" VALUES(58,'paired-vs-independent-t-test',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-29 01:19:56');
INSERT INTO "reviews" VALUES(59,'empirical-rule',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-30 01:18:23');
INSERT INTO "reviews" VALUES(60,'permutations-and-combinations',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-07-31 01:20:11');
INSERT INTO "reviews" VALUES(61,'fundamental-counting-principle',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-01 01:20:22');
INSERT INTO "reviews" VALUES(62,'one-way-anova',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-02 01:18:38');
INSERT INTO "reviews" VALUES(63,'two-way-anova',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-03 01:19:07');
INSERT INTO "reviews" VALUES(64,'post-hoc-tests',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-04 01:20:53');
INSERT INTO "reviews" VALUES(65,'statistical-power',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-05 01:22:59');
INSERT INTO "reviews" VALUES(66,'which-statistical-test-should-i-use',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-06 01:22:05');
INSERT INTO "reviews" VALUES(67,'f-test-f-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-07 01:23:07');
INSERT INTO "reviews" VALUES(68,'sampling-distributions',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-08 01:20:34');
INSERT INTO "reviews" VALUES(69,'poisson-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-09 01:19:33');
INSERT INTO "reviews" VALUES(70,'independent-dependent-mutually-exclusive-events',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-10 01:21:32');
INSERT INTO "reviews" VALUES(71,'hypergeometric-distribution',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-11 01:18:55');
INSERT INTO "reviews" VALUES(72,'regression-assumptions',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-12 01:24:06');
INSERT INTO "reviews" VALUES(73,'multicollinearity-vif',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-13 01:23:16');
INSERT INTO "reviews" VALUES(74,'simpsons-paradox',90,1,'automated routine self-review + green build gate (astro check + vitest + build + link gate)','2026-08-14 01:26:25');
CREATE UNIQUE INDEX idx_kw_global ON keywords(keyword);
CREATE INDEX idx_articles_status ON articles(status);
CREATE INDEX idx_articles_category ON articles(category_slug);
CREATE INDEX idx_keywords_article ON keywords(article_slug);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('keywords',2288);
INSERT INTO "sqlite_sequence" VALUES('reviews',74);
COMMIT;
